### ISSUE TITLE
ltsport. Net 中文网站改版

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#1]
need pics

**Comment by kevin-doselection** [comment]
sent to christin or below
https://www.dropbox.com/sh/pcxivl4yr0ce0b4/AADaqKRqAtOZHwQFR4lRORHYa?dl=0

**Comment by DAXIAPI** [comment]
ok,has been downloaded and sent to christin

**Comment by christinechina** [comment]
ltsport.net 图片修改  double same issue. pls closed this issue.
