### ISSUE TITLE
Walmart.com qty price update

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#10]
沃尔玛产品更新 pls send a task

**Comment by kevin-doselection** [comment]
http://seller.walmart.com
kyang12@go.pasadena.edu
qQ123456!

**Comment by DAXIAPI** [comment]
ok

**Comment by DAXIAPI** [comment]
@kevin-doselection Hi,kevin,I I have downloaded and Inventory.xlsx Price.xlsx,but I'm not sure how to fit in.can you give me an example of Price.xlsx and Inventory.xlsx.pls send it to me,thank you!

**Comment by kevin-doselection** [comment]
Source file from ltsport.com: http://www.ltsport.com/amfeed/main/download/file/walmartfeed.csv/
1. For qty update, you will need sku, qty and lagging time (3 days for all)
2. For price update, you will need sku, price only

**Comment by DAXIAPI** [comment]
ok

**Comment by kevin-doselection** [comment]
Okay, Please do this task everyday.
We want the walmart info is up to date.

**Comment by DAXIAPI** [comment]
okay,got it

**Comment by DAXIAPI** [comment]
@kevin-doselection Hi,kevin,how to match the walmartfeed.csv data to the Inventory.xlsx and Price.xlsx,how do I know which SKU need to be updated,pls tell me,thank!

**Comment by kevin-doselection** [comment]
Since walmart is copy from website, you can update all sku.
for inventory, you just need sku, qty, lagging time (all set 3)
for price, you will need sku, price

**Comment by DAXIAPI** [comment]
okay,got it

**Comment by DAXIAPI** [comment]
@kevin-doselection Hi,kevin,what time to update the price and inventory in China is the best, does not affect the sales of Walmart.

**Comment by kevin-doselection** [comment]
Don't worry about it, you can update it anytime.

**Comment by DAXIAPI** [comment]
ok,got it.

**Comment by kevin-doselection** [comment]
FYI, not only inventory needs to update, but also price information.

**Comment by DAXIAPI** [comment]
@kevin-doselection upload processing result error
[Price.xlsx](https://github.com/kevin-doselection/China-Status/files/441463/Price.xlsx)
![qq 20160829090147](https://cloud.githubusercontent.com/assets/20631720/18038201/71f043b0-6dc7-11e6-9193-9ff00f25a1bd.jpg)

**Comment by kevin-doselection** [comment]
Try download a new template from Seller.walmart.com

**Comment by kevin-doselection** [comment]
Put on hold, Walmart.com is working on it

**Comment by DAXIAPI** [comment]
ok

**Comment by christinechina** [comment]
Hi kevin, 
if this task need stop for a while. pls send jess new test task. thanks.  pls review these task list. 

![image](https://cloud.githubusercontent.com/assets/20959180/18159715/910d3cb6-705c-11e6-99ef-e20f8e1da22b.png)

**Comment by kevin-doselection** [comment]
Let Jess continue working on Daily Walmart qty price update, China website update, and cooperate with SEO.

**Comment by christinechina** [comment]
hi kevin, any update for the problem jess said?

**Comment by DAXIAPI** [comment]
update price still error

**Comment by kevin-doselection** [comment]
Still waiting for their reply

![screen shot 2016-09-07 at 08 51 50](https://cloud.githubusercontent.com/assets/17145866/18318924/65f399aa-74d8-11e6-93a2-ab7b588cda61.png)

**Comment by DAXIAPI** [comment]
ok

**Comment by kevin-doselection** [comment]
The solution has been found.
[Price (1).xlsx](https://github.com/kevin-doselection/China-Status/files/519939/Price.1.xlsx)

**Comment by kevin-doselection** [comment]
Price could be update now.
