### ISSUE TITLE
Walmart.com refund order

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#11]
沃尔玛退款订单 pls send a task

**Comment by kevin-doselection** [comment]
http://seller.walmart.com
kyang12@go.pasadena.edu
qQ123456!

**Comment by DAXIAPI** [comment]
ok

**Comment by DAXIAPI** [comment]
@kevin-doselection I can not understand this part,see the pic below
![qq 20160815112519](https://cloud.githubusercontent.com/assets/20631720/17655010/920c79ee-62db-11e6-94b9-9f416c09442b.jpg)

**Comment by DAXIAPI** [comment]
![qq 20160815113151](https://cloud.githubusercontent.com/assets/20631720/17655048/f022117e-62db-11e6-9250-512e6d8694ed.jpg)
No workable option

**Comment by kevin-doselection** [comment]
Put this on hold.
