### ISSUE TITLE
website product monthly review

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#14]
kevin,pls send us two new PDF

**Comment by Doselectioninc** [comment]
got it

**Comment by Doselectioninc** [comment]
test

**Comment by kevin-doselection** [comment]
[IT 工作进度跟进表.xlsx](https://github.com/kevin-doselection/China-Status/files/412347/IT.xlsx)

**Comment by Doselectioninc** [comment]
[IT 工作进度跟进表.xlsx](https://github.com/kevin-doselection/China-Status/files/412355/IT.xlsx)

**Comment by kevin-doselection** [comment]
1. Use this to download current product atribute
   [download report.pdf](https://github.com/kevin-doselection/China-Status/files/414249/download.report.pdf)
2. Use this excel to find the right method for updating attribute.
   [website product's attributes.pdf](https://github.com/kevin-doselection/China-Status/files/414083/website.product.s.attributes.pdf)

**Comment by DAXIAPI** [comment]
ok,got it

**Comment by kevin-doselection** [comment]
Caution
1. The file should only contains 1 sheet in CSV format.
2. First row should starts with sku.
3. Always make sure the web link is right after submit.
4. Only contain the data you want to update at one time. 
For example, for name update. Use nameUpdate.php link, excel CSV file only can have "sku" "name" column.

Test file:
[test.xlsx](https://github.com/kevin-doselection/China-Status/files/423402/test.xlsx)
You will have to update website product. (www.ltsport.com)

If succeed or failed, let me know.

**Comment by DAXIAPI** [comment]
ok

**Comment by DAXIAPI** [comment]
@kevin-doselection Hi,Kevin,already completed,all successful,pls check up,thank.
![qq 20160818101821](https://cloud.githubusercontent.com/assets/20631720/17759873/c8c5178a-652d-11e6-9ac3-c6117b75987d.jpg)
![qq 20160818101909](https://cloud.githubusercontent.com/assets/20631720/17759874/c8c4ef12-652d-11e6-8072-9225538f5f88.jpg)
![qq 20160818102024](https://cloud.githubusercontent.com/assets/20631720/17759875/c8c86020-652d-11e6-8572-b377b2b55174.jpg)

**Comment by kevin-doselection** [comment]
Okay, now try to export all product data in Magento. (Backup)
Path: system-import/export-dataflow profile-export all product
Check export all field of all products, run profile, run profile in popup
Download file by FTP, var/export/all.csv

**Comment by DAXIAPI** [comment]
already completed

**Comment by kevin-doselection** [comment]
Okay, if you finish the backup export.
You can do the update.

**Comment by DAXIAPI** [comment]
ok

**Comment by kevin-doselection** [comment]
Please update this excel.
[总表website review detail 8-1-2016.xlsx](https://github.com/kevin-doselection/China-Status/files/433276/website.review.detail.8-1-2016.xlsx)

**Comment by DAXIAPI** [comment]
ok

**Comment by DAXIAPI** [comment]
@kevin-doselection has completed the update, pls check it,thank.

**Comment by christinechina** [comment]
Hi jess,  pls export to me for double check. tks

**Comment by kevin-doselection** [comment]
If you checked please let us know, christin. thanks

**Comment by kevin-doselection** [comment]
How's it going?

**Comment by christinechina** [comment]
[website.review.detail.9-1-2016 need RMA double check .xlsx](https://github.com/kevin-doselection/China-Status/files/449078/website.review.detail.9-1-2016.need.RMA.double.check.xlsx)
hi kevin, jess have upload that we have revised. only some left, pls ask RMA dept. check and send us back. and i have send LEO a copy.

**Comment by kevin-doselection** [comment]
Please check is the file can be open, me and RMA cannot open it

**Comment by christinechina** [comment]
[website.review.detail.9-1-2016 need RMA double check .xlsx](https://github.com/kevin-doselection/China-Status/files/451597/website.review.detail.9-1-2016.need.RMA.double.check.xlsx)
and i send you a copy by email.

**Comment by kevin-doselection** [comment]
I downloaded these (from email and here), both cannot open with the same error information.
Picture is fine.

**Comment by kevin-doselection** [comment]
About picture, designer said they just cover the old picture with new text on it.
It is easy, can you ask IT or other people to do it?
For these documents has white background only.

About other buttons, designer will do it.
Since Leo ask them to finish other tasks before he left US.

**Comment by kevin-doselection** [comment]
September review:
Large amount of sku are missing attribute information in all.csv, but is showing on webstie.
Can you check?

**Comment by kevin-doselection** [comment]
Product Review:
URL: http://ltsport.com/update/googleUpdate.php
Update 2 attributes, product_type and google_product_category
There are 386 products are missing these data.

**Comment by DAXIAPI** [comment]
Already completed,Update 2 attributes, product_type and google_product_category.
I downloaded all.csv and I didn't see large amount of sku are missing attribute information in all.csv,can you check it again?

**Comment by kevin-doselection** [comment]
Thanks. Tomorrow will check error code again
