### ISSUE TITLE
ltsport.net 图片修改

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#15]
[California_Resale_Certificate.pdf](https://github.com/kevin-doselection/China-Status/files/412561/California_Resale_Certificate.pdf)
[Credit_Card_Authorization_Form.pdf](https://github.com/kevin-doselection/China-Status/files/412562/Credit_Card_Authorization_Form.pdf)
[LT_Sport_Wholesale_Return_Policy.pdf](https://github.com/kevin-doselection/China-Status/files/412563/LT_Sport_Wholesale_Return_Policy.pdf)
[Wholesale_Account_Application_Form.pdf](https://github.com/kevin-doselection/China-Status/files/412564/Wholesale_Account_Application_Form.pdf)
[Wholesale_Account_Procedures_checklist.pdf](https://github.com/kevin-doselection/China-Status/files/412565/Wholesale_Account_Procedures_checklist.pdf)
[wholesale.xlsx](https://github.com/kevin-doselection/China-Status/files/412566/wholesale.xlsx)

wholesale PDF

**Comment by lihaolihao** [comment]
@kevin-doselection ltsport.net网站修改图片

**Comment by DAXIAPI** [comment]
[KR-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412588/KR-VM-_installation_guide1.pdf)
[KR-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412586/KR-VM-_installation_guide1.pdf)
[KR-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412584/KR-VM-_installation_guide1.pdf)
[CB-SPTU-N-VM-guide.pdf](https://github.com/kevin-doselection/China-Status/files/412578/CB-SPTU-N-VM-guide.pdf)
[Antenna-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412569/Antenna-VM.pdf)
[BR-3BA-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412570/BR-3BA-VM.pdf)
[BR-4BA-VM-guide.pdf](https://github.com/kevin-doselection/China-Status/files/412571/BR-4BA-VM-guide.pdf)
[BR-4BHM-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412572/BR-4BHM-VM-_installation_guide1.pdf)
[BR-TAR-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412573/BR-TAR-VM.pdf)
[Car_Cover-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412574/Car_Cover-VM.pdf)
[CB-BU-4D-VM-guide.pdf](https://github.com/kevin-doselection/China-Status/files/412575/CB-BU-4D-VM-guide.pdf)
[CB-HP0308-guide.pdf](https://github.com/kevin-doselection/China-Status/files/412576/CB-HP0308-guide.pdf)
[CB-PTU-H54-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412577/CB-PTU-H54-VM-_installation_guide1.pdf)
[CB-SPTU-N-VM-guide.pdf](https://github.com/kevin-doselection/China-Status/files/412579/CB-SPTU-N-VM-guide.pdf)
[CB-SPTU-S54-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412580/CB-SPTU-S54-VM-_installation_guide1.pdf)
[CB-SU-4D-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412581/CB-SU-4D-VM-_installation_guide1.pdf)
[Floor_Mat-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412582/Floor_Mat-VM.pdf)
[Floor_Mat-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412583/Floor_Mat-VM-_installation_guide1.pdf)
[RB-4233-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412590/RB-4233-VM.pdf)
[RCB-506-VM-guide.pdf](https://github.com/kevin-doselection/China-Status/files/412591/RCB-506-VM-guide.pdf)
[RCB-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412592/RCB-VM.pdf)
[RN-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412593/RN-VM.pdf)
[Rubber_TM-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412594/Rubber_TM-VM.pdf)
[SC-78S-VM-guide.pdf](https://github.com/kevin-doselection/China-Status/files/412595/SC-78S-VM-guide.pdf)
[Splash_Guard-VM-_installation_guide.pdf](https://github.com/kevin-doselection/China-Status/files/412596/Splash_Guard-VM-_installation_guide.pdf)
[TN-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412598/TN-VM.pdf)
[VM_Moonroof_Visor.pdf](https://github.com/kevin-doselection/China-Status/files/412600/VM_Moonroof_Visor.pdf)
[VSWV-IN-CHANNEL-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412602/VSWV-IN-CHANNEL-VM-_installation_guide1.pdf)
[VSWV-TEPON-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412599/VSWV-TEPON-VM-_installation_guide1.pdf)
[WB-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412601/WB-VM.pdf)
[WC-VM.pdf](https://github.com/kevin-doselection/China-Status/files/412603/WC-VM.pdf)
[KR-VM-_installation_guide1.pdf](https://github.com/kevin-doselection/China-Status/files/412606/KR-VM-_installation_guide1.pdf)
 Video Instructions PDF

**Comment by DAXIAPI** [comment]
![fb_btn](https://cloud.githubusercontent.com/assets/20631720/17579529/30e4a91c-5fc9-11e6-99a4-b54027b09882.png)
![ig_btn](https://cloud.githubusercontent.com/assets/20631720/17579530/30e4fcaa-5fc9-11e6-8c5b-e2f555075760.png)
website pic
![orderd-confirm](https://cloud.githubusercontent.com/assets/20631720/17579525/30e3c862-5fc9-11e6-8548-b3f5c0fa69ac.jpg)
![orderedhelp](https://cloud.githubusercontent.com/assets/20631720/17579526/30e46cc2-5fc9-11e6-8869-c3ba6c1077ad.png)
![part_btn](https://cloud.githubusercontent.com/assets/20631720/17579528/30e48266-5fc9-11e6-9bde-26e27f1eb823.png)
![part_gtn](https://cloud.githubusercontent.com/assets/20631720/17579527/30e46cf4-5fc9-11e6-96bd-755e83cbe112.png)
[return-form.pdf](https://github.com/kevin-doselection/China-Status/files/412610/return-form.pdf)
[success_order.pdf](https://github.com/kevin-doselection/China-Status/files/412611/success_order.pdf)

**Comment by DAXIAPI** [comment]
@kevin-doselection @christinechina Hi,kevin,pls help me translation upload file.

**Comment by christinechina** [comment]
hi kevin, some pics i will send you translation. but the others, such as the guide, wholesale ***. pls ask desinger do first. thanks

**Comment by christinechina** [comment]
ltsport pics need finish on 19th AUG.

**Comment by kevin-doselection** [comment]
Some guide are in the link, under guide folder. The rest is under going
And website pic is under website folder.
please let us know what pic you need, and send it to us.

https://www.dropbox.com/sh/nky8pbyu9jgaa3g/AADb9iEdu6G3eKhCo5wQVUjDa?dl=0

**Comment by DAXIAPI** [comment]
@kevin-doselection Hi,kevin,some pics have been sent to your mailbox.pls check it.

**Comment by Alan1608** [comment]
![a](https://cloud.githubusercontent.com/assets/20963326/17660821/fcd9d032-630d-11e6-96bc-68a4497cc8cb.png)
![c](https://cloud.githubusercontent.com/assets/20963326/17660820/fcd76220-630d-11e6-85df-baa335947c3a.png)
车衣用这种图片,但缺少野外背景色,可以制作或另选一张.突出野外景色
![d](https://cloud.githubusercontent.com/assets/20963326/17660824/00334042-630e-11e6-82fa-26ac699e6067.png)
图二:不需要这张车衣照片,不好看.
![f](https://cloud.githubusercontent.com/assets/20963326/17660822/fd0d7fae-630d-11e6-82ee-29ee16aca26b.png)
![s](https://cloud.githubusercontent.com/assets/20963326/17660823/fd0fb42c-630d-11e6-8b07-b8f58afa1544.png)
车衣照换最右边底下一张,突出野外.

**Comment by Alan1608** [comment]
明天我们需要图片,可以完成吗?

**Comment by kevin-doselection** [comment]
沒辦法，設計師都沒來
要後天

Kevin Yang  
Website Administrator/Manager, Network Administrator, E-Commerce Specialist
Do Selection Inc
Address: 17005 Evergreen Pl, City of Industry CA 91745
Language: English, Chinese (Mandarin, Taiwanese)

**Comment by Alan1608** [comment]
嗯,好的

**Comment by kevin-doselection** [comment]
大圖要什麼?

![br-001](https://cloud.githubusercontent.com/assets/17145866/17717746/8ecdfc14-63c4-11e6-8f1a-dcbf5b4e1971.jpg)
![cb-002](https://cloud.githubusercontent.com/assets/17145866/17717742/8ec28276-63c4-11e6-989d-d2e1ee3d278c.jpg)
![cb001](https://cloud.githubusercontent.com/assets/17145866/17717744/8ecc8dde-63c4-11e6-8073-02b3b6ff8c86.jpg)
![cc 001](https://cloud.githubusercontent.com/assets/17145866/17717743/8ec41de8-63c4-11e6-9676-c826a34179b7.jpg)
![kb 003](https://cloud.githubusercontent.com/assets/17145866/17717745/8eccc786-63c4-11e6-8712-1af7c2c5484a.jpg)

**Comment by Alan1608** [comment]
![default](https://cloud.githubusercontent.com/assets/20963326/17721198/0439e0e4-645b-11e6-90aa-182f954dc88b.png)
大图需要这样风格的图片,特征:户外驾驶,出现汽车全身照,车顶安装"行李箱"或"行李框".尽量突出山清水秀的背景色.尺寸:1060*500

![20160817092528](https://cloud.githubusercontent.com/assets/20963326/17721423/9f643870-645c-11e6-8d04-b8af2cf7d071.png)

**Comment by kevin-doselection** [comment]
![br-001](https://cloud.githubusercontent.com/assets/17145866/17781716/4fe0335c-6525-11e6-9b89-cc45b77738da.jpg)
![cb-002](https://cloud.githubusercontent.com/assets/17145866/17781715/4fd96b62-6525-11e6-9708-0d8e7f24ab15.jpg)
![cb001](https://cloud.githubusercontent.com/assets/17145866/17781714/4fd894d0-6525-11e6-8de9-222f63ef77ba.jpg)
![cc 001](https://cloud.githubusercontent.com/assets/17145866/17781712/4fd6cf7e-6525-11e6-85a6-9db4e928f34f.jpg)
![cp 18](https://cloud.githubusercontent.com/assets/17145866/17781713/4fd76290-6525-11e6-92b4-2b8e05b9eec5.jpg)
![kb 002](https://cloud.githubusercontent.com/assets/17145866/17781717/4ff8f126-6525-11e6-9383-0c2052d26b45.jpg)
![kb 003](https://cloud.githubusercontent.com/assets/17145866/17781718/4ffd5c48-6525-11e6-8333-d331a3c8025d.jpg)
![sb 001](https://cloud.githubusercontent.com/assets/17145866/17781719/4fffed78-6525-11e6-9686-6a59637e4d47.jpg)

**Comment by christinechina** [comment]
Hi kevin, 
pics looks not good.  this three need revised. need much more fashion. The pixel is too low. cant see clearly. 
pls ask designer send it back on monday. 
![qq 20160819094302](https://cloud.githubusercontent.com/assets/20959180/17796173/56922c38-65f1-11e6-84bc-9619e31db6da.jpg)

![qq 20160819094631](https://cloud.githubusercontent.com/assets/20959180/17796234/d3c60cba-65f1-11e6-82a2-8909888ed93f.jpg)

**Comment by kevin-doselection** [comment]
Working on it

**Comment by kevin-doselection** [comment]
What do you mean?
pixel or color not too bright?

**Comment by christinechina** [comment]
both

**Comment by christinechina** [comment]
![img_7080](https://cloud.githubusercontent.com/assets/20959180/17920290/4848928e-6a06-11e6-8bc4-6056e88cee91.JPG)
![img_7081](https://cloud.githubusercontent.com/assets/20959180/17920300/53db3462-6a06-11e6-915b-bc19b783465f.JPG)
for reference only. pls help to transfer to designer .

**Comment by kevin-doselection** [comment]
Please see below
![br-001](https://cloud.githubusercontent.com/assets/17145866/17940720/35ca4f92-69e5-11e6-8a3d-0002ae37669b.jpg)
![cb-002](https://cloud.githubusercontent.com/assets/17145866/17940718/35c3b20e-69e5-11e6-9519-df826da6d6d4.jpg)
![cb001](https://cloud.githubusercontent.com/assets/17145866/17940719/35ca7184-69e5-11e6-96a9-69366f4b7319.jpg)
![cc 001](https://cloud.githubusercontent.com/assets/17145866/17940722/35d585ce-69e5-11e6-82d7-6dae33824430.jpg)
![cp 18](https://cloud.githubusercontent.com/assets/17145866/17940721/35cd0aa2-69e5-11e6-862b-f7bbdf5be7cf.jpg)
![kb 003](https://cloud.githubusercontent.com/assets/17145866/17940723/365dbad4-69e5-11e6-8ce6-1436005549b3.jpg)
![sb 001](https://cloud.githubusercontent.com/assets/17145866/17940724/36c1a756-69e5-11e6-9e73-419a0817daf3.jpg)

**Comment by christinechina** [comment]
![image](https://cloud.githubusercontent.com/assets/20959180/17993888/acd92138-6b86-11e6-86e3-657f8ba48893.png)

![image](https://cloud.githubusercontent.com/assets/20959180/17993892/b1eaa0e8-6b86-11e6-8144-85486a40665c.png)

still no good. pls ask desinger revise again. tks

**Comment by kevin-doselection** [comment]
![br-001](https://cloud.githubusercontent.com/assets/17145866/18015086/f8897eae-6b7a-11e6-8d7d-bb848a7dad69.jpg)
![cc 001](https://cloud.githubusercontent.com/assets/17145866/18015085/f886f54e-6b7a-11e6-8b3b-504a2105a177.jpg)

**Comment by christinechina** [comment]
need one more pics, pls ask desinger do that.  this one for reference only.  @kevin-doselection 
![news_00](https://cloud.githubusercontent.com/assets/20959180/18072925/a80a1ad4-6e94-11e6-8cbd-4dc7e65e023a.jpg)

**Comment by christinechina** [comment]
hi kevin, any update?

**Comment by kevin-doselection** [comment]
They are making video these day, latest day you will get picture is 9/7 (Wed)

**Comment by kevin-doselection** [comment]
![bss men 01](https://cloud.githubusercontent.com/assets/17145866/18294750/69ae9168-7450-11e6-9469-182d9e2f3130.jpg)

**Comment by DAXIAPI** [comment]
got it
