### ISSUE TITLE
SEOEN

### ISSUE THREAD

**Issue by Alan1608** [kevin-doselection/951753258#16]

**Comment by lihaolihao** [comment]
aaa

**Comment by christinechina** [comment]
hi kevin, alan is tour website SEO/SEM handler, pls add him. and he will communicate with you here.  ENCLOSED is his schedule. pls check.thanks
[SEO 工作跟进表.xlsx](https://github.com/kevin-doselection/China-Status/files/412954/SEO.xlsx)

**Comment by kevin-doselection** [comment]
issue 5 and 6 download link https://www.dropbox.com/sh/pcxivl4yr0ce0b4/AADaqKRqAtOZHwQFR4lRORHYa?dl=0

現在ltsport.net在中國搜尋市場上，表現如何

**Comment by christinechina** [comment]
我先回复一下您的问题，ltsport.net 让在等您在跟进的图片。因此暂未体验效果。他已发布部分品牌介绍文章。 你可到百度搜索测试排名。  alan 请跟进。

**Comment by Alan1608** [comment]
由于暂时上传不了文件,我已把文件发邮箱给你了.请查收.
