### ISSUE TITLE
淘宝晴雨挡主图 5张

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#17]
[淘宝晴雨挡主图需求.xlsx](https://github.com/kevin-doselection/China-Status/files/415041/default.xlsx)

hi kevin, pls ask design follow.  finsh ltsport.net pics  first, then start taobao pics design. tks. 
ltsport pics need finish on 19th AUG. 

this one finish on 24th AUG. 

pls reply me ok or not?

**Comment by kevin-doselection** [comment]
Okay

**Comment by kevin-doselection** [comment]
Taobao I create a sample template before. Did you see that?

**Comment by christinechina** [comment]
主图是这里显示。 要5张大图。 
![qq 20160822111319](https://cloud.githubusercontent.com/assets/20959180/17842831/758be38a-6859-11e6-9365-110bfddeb6c2.jpg)
https://item.taobao.com/item.htm?id=536199830332

**Comment by kevin-doselection** [comment]
working on it

**Comment by kevin-doselection** [comment]
![br-001](https://cloud.githubusercontent.com/assets/17145866/17942205/4d06d9cc-69eb-11e6-9bb9-b3b2d74d7caa.jpg)
![cb-002](https://cloud.githubusercontent.com/assets/17145866/17942210/4d27472a-69eb-11e6-92ea-4816df071c2e.jpg)
![cb001](https://cloud.githubusercontent.com/assets/17145866/17942207/4d22df78-69eb-11e6-9579-e6a68c541c2f.jpg)
![cc 001](https://cloud.githubusercontent.com/assets/17145866/17942208/4d25272e-69eb-11e6-8301-4df8b6e37804.jpg)
![cp 18](https://cloud.githubusercontent.com/assets/17145866/17942209/4d25e65a-69eb-11e6-9f7f-f6fe55be75ed.jpg)
![kb 003](https://cloud.githubusercontent.com/assets/17145866/17942211/4d27806e-69eb-11e6-9682-3e8d78614cbc.jpg)
![sb 001](https://cloud.githubusercontent.com/assets/17145866/17942206/4d1ccade-69eb-11e6-938b-d747468d04e3.jpg)

**Comment by christinechina** [comment]
主图是这里显示。 要5张大图。  
https://item.taobao.com/item.htm?id=536199830332
![758be38a-6859-11e6-9365-110bfddeb6c2](https://cloud.githubusercontent.com/assets/20959180/18160022/f1224096-705d-11e6-8e65-fa31cbb271db.jpg)

h kevin, this five pics, finishe or not ？pls follow up. thanks

**Comment by kevin-doselection** [comment]
They are making video these day, latest day you will get picture is 9/7 (Wed)

**Comment by kevin-doselection** [comment]
![taoboa-list pic-01](https://cloud.githubusercontent.com/assets/17145866/18322864/b23ad1aa-74e9-11e6-91bd-51ae8dd8bad2.jpg)
![taoboa-list pic-02](https://cloud.githubusercontent.com/assets/17145866/18322860/b2335768-74e9-11e6-9b3c-afc75386d76d.jpg)
![taoboa-list pic-03](https://cloud.githubusercontent.com/assets/17145866/18322863/b2376024-74e9-11e6-91f1-778d0fe74073.jpg)
![taoboa-list pic-04](https://cloud.githubusercontent.com/assets/17145866/18322861/b2354d34-74e9-11e6-99d1-ebb5a29581bd.jpg)
![taoboa-list pic-05](https://cloud.githubusercontent.com/assets/17145866/18322862/b2365c38-74e9-11e6-8e58-64e65a01910f.jpg)
