### ISSUE TITLE
.net Pictures and pdf  translation

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#18]
@kevin-doselection Hi,kevin,pls download the file,need to translate,thank you!
https://www.dropbox.com/s/yeu6a5jnkzi6nq8/pic.zip?dl=0

**Comment by christinechina** [comment]
hi kevin,  already translate into chinese. pls ask designer help to make pics for us, by the excel that above, jess sent. thanks.

**Comment by kevin-doselection** [comment]
Mail received. Sent to designer already. Waiting for result

**Comment by DAXIAPI** [comment]
ok

**Comment by kevin-doselection** [comment]
![br-001](https://cloud.githubusercontent.com/assets/17145866/17781687/33bd9d04-6525-11e6-8591-aa2ac5719e8b.jpg)
![cb-002](https://cloud.githubusercontent.com/assets/17145866/17781686/33bb440a-6525-11e6-81d7-f7f75803fc3a.jpg)
![cb001](https://cloud.githubusercontent.com/assets/17145866/17781685/33baf004-6525-11e6-9899-d886afa867ee.jpg)
![cc 001](https://cloud.githubusercontent.com/assets/17145866/17781689/33bf897a-6525-11e6-9b48-f52548d6927f.jpg)
![cp 18](https://cloud.githubusercontent.com/assets/17145866/17781688/33bee524-6525-11e6-9505-204f1e2fb628.jpg)
![kb 002](https://cloud.githubusercontent.com/assets/17145866/17781691/33d51a1a-6525-11e6-936a-b77e9c135b69.jpg)
![kb 003](https://cloud.githubusercontent.com/assets/17145866/17781690/33d2a4ec-6525-11e6-9363-275468af47de.jpg)
![sb 001](https://cloud.githubusercontent.com/assets/17145866/17781692/33db37ba-6525-11e6-954c-6400e47d3118.jpg)

**Comment by kevin-doselection** [comment]
Do you need anything from designer?

**Comment by kevin-doselection** [comment]
Guide video all translated, but PDF still need China translate text

**Comment by DAXIAPI** [comment]
PDF China translate text
https://www.dropbox.com/sh/x6b7usek2syeq5c/AADSmcXAptGB7J9vz7wMLx2Ua?dl=0

**Comment by kevin-doselection** [comment]
Sent to designer

**Comment by DAXIAPI** [comment]
okay，got it

**Comment by kevin-doselection** [comment]
![antenna-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951917/d1da708a-6a1a-11e6-9b3b-786a679e807e.jpg)
![br-3ba-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951916/d1d909de-6a1a-11e6-8e8b-f3b3723d54c2.jpg)
![br-4bhm-vm- installation guide1-0123](https://cloud.githubusercontent.com/assets/17145866/17951918/d1da6572-6a1a-11e6-8bf1-f7bdc91d17e3.png)
![cb-902-s44-guide-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951915/d1d53a7a-6a1a-11e6-8916-53b38cad836d.jpg)
![cb-bu-4d-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951914/d1d3c4d8-6a1a-11e6-99df-76bb4f4ac60c.jpg)
![cb-ptu-h54-vm- installation guide1-0123](https://cloud.githubusercontent.com/assets/17145866/17951919/d1eaf63a-6a1a-11e6-8450-a7e252cc9e95.jpg)
![cb-sptu-n-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951920/d1ec723a-6a1a-11e6-9925-c0b00f4763ab.jpg)
![cb-sptu-s54-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951921/d1f10692-6a1a-11e6-831a-c8cd4a4a90ad.jpg)
![cb-su-4d-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951922/d1f61876-6a1a-11e6-8c16-b58a46465969.jpg)
![install-wb-vm](https://cloud.githubusercontent.com/assets/17145866/17951923/d1f82594-6a1a-11e6-8ed2-3ef756d8fca4.png)
![kr-n1- installation guide1](https://cloud.githubusercontent.com/assets/17145866/17951924/d205d5d6-6a1a-11e6-946a-2e337c87909e.jpg)
![kr-vm- installation guide1-0123](https://cloud.githubusercontent.com/assets/17145866/17951925/d207b2a2-6a1a-11e6-977e-3eff13cb25dc.png)
![moonroof visor-guide-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951926/d213aff8-6a1a-11e6-8487-7cc66e515c58.jpg)
![rb-4233-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951927/d2233482-6a1a-11e6-8597-89a2b342cc53.png)
![rn-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951928/d223c46a-6a1a-11e6-80ce-2a530eff5cee.jpg)
![rubber fm-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951929/d225d85e-6a1a-11e6-82d0-c414e96045c8.jpg)
![rubber tm-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951930/d2266742-6a1a-11e6-839c-ee843b2da290.jpg)
![splash guard-vm- installation guide1-0123](https://cloud.githubusercontent.com/assets/17145866/17951931/d22e22a2-6a1a-11e6-9162-052c190fa054.png)
![tn-vm-chi](https://cloud.githubusercontent.com/assets/17145866/17951932/d232244c-6a1a-11e6-8b36-c5133416dda4.jpg)
![vm-car cover](https://cloud.githubusercontent.com/assets/17145866/17951933/d23ff43c-6a1a-11e6-893f-2c97114dbc7d.jpg)
![vswv-in-channel-vm- installation guide1-0123](https://cloud.githubusercontent.com/assets/17145866/17951934/d244601c-6a1a-11e6-84b7-50d1a394cdbe.png)

**Comment by christinechina** [comment]
some word need revised. pls see attachment and transfer to designer. tks. @kevin-doselection 
[guide need revised.xlsx](https://github.com/kevin-doselection/China-Status/files/436511/guide.need.revised.xlsx)

**Comment by kevin-doselection** [comment]
Sent to designer.

**Comment by christinechina** [comment]
thank you. pls tell me when can finish?

**Comment by kevin-doselection** [comment]
Before next Tue.

**Comment by kevin-doselection** [comment]
Designer is not coming today, wait to tomorrow

**Comment by christinechina** [comment]
OK. pls speed up. tks

**Comment by kevin-doselection** [comment]
They are making video these day, latest day you will get picture is 9/7 (Wed)

**Comment by kevin-doselection** [comment]
![antenna-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331003/d58d3586-7510-11e6-816a-db2b8bd40056.jpg)
![br-3ba-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331004/d58f3e4e-7510-11e6-94a1-f7acbc2aa141.jpg)
![br-4bhm-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331006/d594a668-7510-11e6-8366-d1ea413df4c6.jpg)
![car cover-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331005/d590b080-7510-11e6-9130-7dde209f9577.jpg)
![cb-902-s44-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331008/d61ffe52-7510-11e6-9197-0ec31ff3cc5d.jpg)
![cb-bu-4d-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331007/d61ea106-7510-11e6-9921-f410c2512534.jpg)
![cb-ptu-h54-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331009/d62759f4-7510-11e6-8929-14155d8ce2b2.jpg)
![cb-sptu-n-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331012/d6b4a5e8-7510-11e6-83b3-589adfb13a1d.jpg)
![cb-sptu-s54-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331011/d6b2e50a-7510-11e6-868e-ca8fe83cc63a.jpg)
![cb-su-4d-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331013/d6c11562-7510-11e6-9322-7f92d9528c6f.jpg)
![kr253-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331014/d6d9bbf8-7510-11e6-8722-38ed3964dacb.png)
![moonroof visor-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331016/d7466b36-7510-11e6-9876-a17d746b0efd.jpg)
![rb-4233-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331015/d7435734-7510-11e6-8350-a3ec125e93c7.jpg)
![rubber fm-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331017/d74e682c-7510-11e6-9f24-a4833011ab4a.jpg)
![rubber tm-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331018/d75a1dca-7510-11e6-9ad0-eb96e9e28a12.jpg)
![splash guard-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331020/d7ee0a1c-7510-11e6-8f73-92b097698ab2.jpg)
![tn-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331019/d7dd5a8c-7510-11e6-95dd-c61ee27f17ca.jpg)
![tn-vm-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331021/d7ee9c20-7510-11e6-92f2-dca2709a64e1.jpg)
![vswv-in-channel-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331023/d869ea2e-7510-11e6-9377-42d96a4000e9.jpg)

![wb-guide-chi](https://cloud.githubusercontent.com/assets/17145866/18331024/d87d1d1a-7510-11e6-8b57-2710edb9d368.png)

**Comment by christinechina** [comment]
[PDF更改.xlsx](https://github.com/kevin-doselection/China-Status/files/463705/PDF.xlsx)
 need revised again @kevin-doselection

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/bp9az9viiqn67qb/AAA9QeEubnDWqui2hn1-4345a?dl=0

**Comment by DAXIAPI** [comment]
@kevin-doselection The pattern changed to "Video" pattern, "TERMS&SERVICE" text changed to "GUIDE VIDEO" text.thank!
![terms-after](https://cloud.githubusercontent.com/assets/20631720/18700725/605b88d4-800b-11e6-868f-da959d970ffc.png)

**Comment by DAXIAPI** [comment]
![about_us-after](https://cloud.githubusercontent.com/assets/20631720/18702045/7e6cc44e-8012-11e6-8054-afcd28d1f007.png)
![account-after](https://cloud.githubusercontent.com/assets/20631720/18702049/7e727376-8012-11e6-8ca4-3bd72d8aa926.png)
![appoint-after](https://cloud.githubusercontent.com/assets/20631720/18702058/80b6c2c2-8012-11e6-87aa-ddb70b852767.png)
![contact-after](https://cloud.githubusercontent.com/assets/20631720/18702048/7e70cc6a-8012-11e6-84fb-5da87f7bc03b.png)
![my_order-after](https://cloud.githubusercontent.com/assets/20631720/18702047/7e7032e6-8012-11e6-8643-f139d49f95da.png)
![order-after](https://cloud.githubusercontent.com/assets/20631720/18702046/7e703570-8012-11e6-8d95-3533ca865240.png)
![products-after](https://cloud.githubusercontent.com/assets/20631720/18702051/7eab7dc4-8012-11e6-8ffa-36f2ff062929.png)
![return-after](https://cloud.githubusercontent.com/assets/20631720/18702052/7eacf014-8012-11e6-83c1-23bac3884859.png)
![shop-by-product-after](https://cloud.githubusercontent.com/assets/20631720/18702053/7ead38d0-8012-11e6-847a-0b2b4815a198.png)
![shop-by-vehicle-after](https://cloud.githubusercontent.com/assets/20631720/18702054/7edbcac4-8012-11e6-8815-178cea2f4d80.png)
![terms-after](https://cloud.githubusercontent.com/assets/20631720/18702055/7ee2efca-8012-11e6-9282-f7b93d1771c4.png)
[中文翻译.xlsx](https://github.com/kevin-doselection/China-Status/files/484418/default.xlsx)
see files "中文翻译.xlsx", which have Chinese translation. Please ask the designer to modify the pic,English text ps into Chinese text.thank!

**Comment by DAXIAPI** [comment]
@kevin-doselection Hi,kevin,is it in processing now?

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/ohygq5fsd18mtmn/AADVqCt_pRGWz-3g9fNKSlZ1a?dl=0

**Comment by christinechina** [comment]
hi kevin, pls send me all installation guide PSD format. Thanks. @kevin-doselection

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/lxz9mwrec1dumi0/AACT9hVYCaidWJY9XOQ7WT_wa?dl=0
