### ISSUE TITLE
工作跟进表

### ISSUE THREAD

**Issue by Alan1608** [kevin-doselection/951753258#19]

**Comment by Alan1608** [comment]
[IT&SEO 工作跟进表.xlsx](https://github.com/kevin-doselection/China-Status/files/424553/IT.SEO.xlsx)

**Comment by christinechina** [comment]
alan, pls update SEO工作跟进表 trm.  请明天更新 SEO 工作跟进表， 谢谢。

**Comment by christinechina** [comment]
[IT.SEO.xlsx](https://github.com/kevin-doselection/China-Status/files/426166/IT.SEO.xlsx)  
hi alan,下次最好用这个网站发给我。 每周可更新一次。 因为其他同事如KEVIN, Leo, 都想知道你的工作进度。及时协助你完成。 

hi leo,kevin, pls dowmload attachment and have a look. any qustion,pls contact us.

**Comment by DAXIAPI** [comment]
IT工作跟进表
[IT.xlsx](https://github.com/kevin-doselection/China-Status/files/426677/IT.xlsx)

**Comment by Alan1608** [comment]
[IT&SEO 工作跟进表.xlsx](https://github.com/kevin-doselection/China-Status/files/426691/IT.SEO.xlsx)

OK 已更新
