### ISSUE TITLE
googel trust code 

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#2]
Google产品验证

**Comment by DAXIAPI** [comment]
[Google Trusted Stores code.pdf](https://github.com/kevin-doselection/China-Status/files/412401/Google.Trusted.Stores.code.pdf)

**Comment by DAXIAPI** [comment]
Google Trusted Stores code upload

**Comment by christinechina** [comment]
hi kevin, jess have finished to add the code on our website.  if no problem. pls close this issue. tks.

**Comment by kevin-doselection** [comment]
Where did you place the badge code?

**Comment by DAXIAPI** [comment]
@kevin-doselection I put it in page/html/head.phtml,It doesn't work?

**Comment by kevin-doselection** [comment]
Google server error. Fixed
