### ISSUE TITLE
website review detail

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#20]
@kevin-doselection Hi,kevin,这是车型表检查有问题的地方，已经修改完成，请在ltsport.com中检查对应的问题
[website review detail 8-11 .xlsx](https://github.com/kevin-doselection/China-Status/files/424565/website.review.detail.8-11.xlsx)

**Comment by christinechina** [comment]
hi kevin, pls help to follow untill RMA dept send bact to us. thank you so much.

**Comment by kevin-doselection** [comment]
Sent to RMA dept

**Comment by DAXIAPI** [comment]
ok

**Comment by kevin-doselection** [comment]
working on it

**Comment by DAXIAPI** [comment]
ok

**Comment by christinechina** [comment]
dear all. it's double with another task.  so close this one.
