### ISSUE TITLE
CB-FR-95 attribute update

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#21]
CB-FR-95 attribute update

SKU: CB-FR-95-201-WS
Attribute: year, make, model, sub-model, pdata(vehicle fitment)
![screen shot 2016-08-24 at 11 28 57](https://cloud.githubusercontent.com/assets/17145866/17942887/1dd0c9ee-69ee-11e6-80b4-e6477a1f392e.png)

Data source: 
[CB-FR-95.pdf](https://github.com/kevin-doselection/China-Status/files/435422/CB-FR-95.pdf)

**Comment by DAXIAPI** [comment]
@kevin-doselection already completed,pls check it,thank.
![image](https://cloud.githubusercontent.com/assets/20631720/17956129/f16011ae-6ab9-11e6-92c5-7b6da31e288f.png)

**Comment by kevin-doselection** [comment]
Sent to RMA dept to check.

**Comment by kevin-doselection** [comment]
Another task:

sku: all CB-SU
attribute: pdata(vehicle fitment) remove every scion Xb

**Comment by DAXIAPI** [comment]
ok

**Comment by DAXIAPI** [comment]
already completed,pls check it,thank.
