### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#22]
SEO, do you have idea to improve ltsport.net exposure in China?
Not only website itself, but also qq, baido etc.
And so far how many improvement did you do, besides Meta information.

**Comment by christinechina** [comment]
[里浩车品营销方案.pptx](https://github.com/kevin-doselection/China-Status/files/438923/default.pptx)
[SEO网站优化方案.pptx](https://github.com/kevin-doselection/China-Status/files/438925/SEO.pptx)
HI kevin, that's the plan alan send me. pls have a look.  He is working following these plan. pls transfer to LEO too.  any suggestion flee free to contact us. thanks

**Comment by Alan1608** [comment]
[SEO 工作跟进表.xlsx](https://github.com/kevin-doselection/China-Status/files/438915/SEO.xlsx)
最近都有用QQ群曝光ltsport.net网站.QQ比较时效性.但不好 的是大多数不能直接发广告.会被T.
百度知道,百度文库,博客,论坛,贴吧,分类信息网等都已经有账号.现在站外免费的曝光只能通过这些渠道留下网站的链接进而曝光产品.

**Comment by kevin-doselection** [comment]
環境分析
第二點
同樣銷售Window Visor, Mats, roof rack有哪些商店
第三點
女性有車族在市場比例多少

市場細分
第三點
請提供三個同業間中上等的網站，作為參考

4P策略組合
第四點  (*)
目前百度搜尋進度
文章更新進度
站外優化進度

**Comment by kevin-doselection** [comment]
一、
（一）結構修改在現今的網站容易嗎？
（二）（三）網站地圖優先製作 sitemap
（四）針對大陸用戶對各產品產生合適的關鍵字，產品優先
二、
（一）報章、雜誌、書籍預期從何處取得
（二）站長工具可以啟用
（三）同一、（四）
（四）可以舉例嗎？像是產品頁中連到何處
三、
（二）目前其他業者也做類似的活動嗎？
四、
（一）請提供過去一個月統計圖表作為參考
（二）可以提取其他業者的關鍵字作為己用

**Comment by christinechina** [comment]
got it. alan, copy that.

**Comment by Alan1608** [comment]
[環境分析.docx](https://github.com/kevin-doselection/China-Status/files/444458/default.docx)
在同行网站中,他们大多通过第三方平台(淘宝天猫京东一号店卖产品)销售产品,他们自己的网站都是内容站,不是购物网站.从内容站链接到他们的第三方商店.与我们站出发点不一样.
脚垫同行的有:
御马:http://www.yumachina.com/天猫淘宝店:https://yumacp.tmall.com/shop/view_shop.htm京东店:http://masyuma.jd.com/
御马占有脚垫市场32%的份额.
五福金牛:天猫淘宝店:https://wfjn.tmall.com/京东店:http://mall.jd.com/index-1000001798.html
五福金牛占有脚垫市场22%的份额.

**Comment by kevin-doselection** [comment]
很好，我們會研究這些文件
