### ISSUE TITLE
China status

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#24]
Christin,
how is China website doing so far in your perspective?

**Comment by christinechina** [comment]
hi kevin, 
now we still wiating for designer send back pics. Price of products haven't confirm yet. and leo help us matching model list, china to usa. The other pages  of website have finished  and no problem.

**Comment by christinechina** [comment]
jess, pls send pic of every page. tks @lihaolihao

**Comment by christinechina** [comment]
Have a look these pics. pages of  chinses website. 

![lt sport - ltsport com](https://cloud.githubusercontent.com/assets/20959180/18042635/18bab7d4-6df5-11e6-81b2-d64a648dbe7f.png)

![products - ltsport com](https://cloud.githubusercontent.com/assets/20959180/18042746/be1ca930-6df5-11e6-8484-76b9fcb38a31.png)

![qq 20160829091411](https://cloud.githubusercontent.com/assets/20959180/18042805/283b772e-6df6-11e6-9d3b-0dd07c3c3b3d.jpg)

![customer login - ltsport com](https://cloud.githubusercontent.com/assets/20959180/18042688/526259a6-6df5-11e6-8e58-a7def1acefc9.png)
![roof basket - ltsport com]
![- ltsport com](https://cloud.githubusercontent.com/assets/20959180/18042928/f7a16e10-6df6-11e6-80a1-d6c907c87584.png)
![- ltsport com](https://cloud.githubusercontent.com/assets/20959180/18042937/0b866b42-6df7-11e6-97fe-120cd1dd5618.png)
![- ltsport com](https://cloud.githubusercontent.com/assets/20959180/18043099/2b1bdb58-6df8-11e6-9456-d42dfb77b207.png)
![- ltsport com](https://cloud.githubusercontent.com/assets/20959180/18043228/186de838-6df9-11e6-884a-71d395af39e9.png)
![ltsport com](https://cloud.githubusercontent.com/assets/20959180/18043370/fc97c542-6df9-11e6-9fab-878d29244d5c.png)

(https://cloud.githubusercontent.com/assets/20959180/18042822/51195d50-6df6-11e6-84ee-c35663326d9f.png)
![- ltsport com](https://cloud.githubusercontent.com/assets/20959180/18042892/b0cfa286-6df6-11e6-90b0-6bf13d744141.png)

**Comment by christinechina** [comment]
Hi kevin, because mate still reviseding. so Jess haven't upload this chinese new format. and haven't upload chinese product description.  pis for refreence only. thanks.

**Comment by kevin-doselection** [comment]
Sorry Christin, i don't understand.

**Comment by christinechina** [comment]
Alan 在做中文网站内部优化，所以新版本未上传上网。 图片是新版中文网站的效果图。 你看看。 基本完成。

**Comment by christinechina** [comment]
hi kevin understand or not? any question feel free contact us. now we are instering payment method.  once finshed, will update status.

**Comment by kevin-doselection** [comment]
Good, after finish let me know. No question so far until I test it.

**Comment by kevin-doselection** [comment]
Hi, data from Designer
https://www.dropbox.com/sh/0l6qyxaajdxl006/AABERWTNs_5H-GkXvpTaMruoa?dl=0

**Comment by christinechina** [comment]
hi kevin, pls tell us what we need to do when you send us task. tks. so above pics we need translate ?? double check??

**Comment by kevin-doselection** [comment]
Above picture are the result from our designer. She said it's assigned from Leo for China TaoBao.
It was requested from your office to Leo I believe.

**Comment by christinechina** [comment]
hi, kevin. enclosed a excel that tell where need to revised. pls transfer to designer. Then follow untill he send  it back. Thanks
