### ISSUE TITLE
magento onepage checkout problem

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#25]
@kevin-doselection Hi,kevin,Do you know how to solve the "Fatal error: Call to a member function setMethod() on a non-object in /var/www/html/app/code/core/Mage/Payment/Helper/Date.php 106",now can't magento onepage checkout.

**Comment by kevin-doselection** [comment]
Which page causes this error? And what action did you do.

Ref 1: http://stackoverflow.com/questions/2922895/when-loading-shopping-cart-in-magento-with-a-new-payment-module-i-get-an-error
Ref 2: http://magento.stackexchange.com/questions/31517/magento-fatal-error-call-to-a-member-function-getmethodinstance-on-a-non-obje

**Comment by DAXIAPI** [comment]
I search the question,but it's not working.page  /checkout/onepage/
![qq 20160907172400](https://cloud.githubusercontent.com/assets/20631720/18306776/f22c6900-751f-11e6-8159-38591364a2aa.jpg)

**Comment by kevin-doselection** [comment]
Give me a customer account that I can try.

**Comment by DAXIAPI** [comment]
123456@qq.com/a123456
![image](https://cloud.githubusercontent.com/assets/20631720/18335031/a3105a68-75ae-11e6-9e65-b5541d0be8fb.png)

**Comment by kevin-doselection** [comment]
![screen shot 2016-09-08 at 11 14 09](https://cloud.githubusercontent.com/assets/17145866/18361057/6305836a-75b5-11e6-8c4c-f21cd800c6eb.png)
Any problem?

**Comment by DAXIAPI** [comment]
pls try again,thank!

**Comment by kevin-doselection** [comment]
cannot login

**Comment by DAXIAPI** [comment]
2634563010@qq.com/a123456,try this.
