### ISSUE TITLE
Trust store code

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#26]
URL: https://support.google.com/trustedstoresmerchant/answer/6063075

4 Error:
![screen shot 2016-09-06 at 16 52 52](https://cloud.githubusercontent.com/assets/17145866/18294989/766b8d3c-7452-11e6-9e2a-7aae9f6026a9.png)
![screen shot 2016-09-06 at 16 52 59](https://cloud.githubusercontent.com/assets/17145866/18294991/76a054e0-7452-11e6-8a20-71ecf0112bb4.png)
![screen shot 2016-09-06 at 16 53 10](https://cloud.githubusercontent.com/assets/17145866/18294990/769d7324-7452-11e6-9ee3-e5d3e6d6deb8.png)
![screen shot 2016-09-06 at 16 53 06](https://cloud.githubusercontent.com/assets/17145866/18294992/76a336e2-7452-11e6-9e08-9723bf454eb2.png)

**Comment by DAXIAPI** [comment]
what is gts-i-prodesearch-id and google_base_offer__id?

**Comment by kevin-doselection** [comment]
Google Account ID is 699026
Shopping Item ID is GTIN, different products would have different GTIN

**Comment by DAXIAPI** [comment]
I added these,pls check it,thank you!
![qq 20160908094653](https://cloud.githubusercontent.com/assets/20631720/18334343/549dd748-75a9-11e6-84ef-6224008114cb.jpg)
![qq 20160908094715](https://cloud.githubusercontent.com/assets/20631720/18334344/54a00c52-75a9-11e6-8a08-06a9be8afdd7.jpg)

**Comment by kevin-doselection** [comment]
Great!
