### ISSUE TITLE
website fitment fix

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#29]
excel included sku that need to fix year, make, model
[require fitment fix.xlsx](https://github.com/kevin-doselection/China-Status/files/470834/require.fitment.fix.xlsx)

**Comment by kevin-doselection** [comment]
Waiting:
China-data
Ivee-price

**Comment by kevin-doselection** [comment]
[description_missing_fitment.xlsx](https://github.com/kevin-doselection/China-Status/files/471050/description_missing_fitment.xlsx)

Problem column: Description
Example:
LT Sport&reg; Brand Cargo Net. Item(s) Ready to Ship from United States. Roof Cargo Net Attaches to the Roof Carrier Basket and Safely Secures Cargo In Place. Perfect for Keeping Items From Moving. Made from Rubber. 100% Brand New in Box (Installation Hardware Included). Flexible and Elastic. (Professional Installation is Always Recommended). Size: 37"W x 37"W  

> Will Fit 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 91 92 93 94 95 96 97 98 99 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 Audi 100 100 Quattro 80 80 Quattro A3 A4 A4 Quattro A6 A6 Quattro Allroad Quattro Q7

All product should have fitment info in description.
If missing please add it, year(2 digits and 4 digits), make, model

**Comment by kevin-doselection** [comment]
Is it in processing now?

**Comment by christinechina** [comment]
pls see attachment. most of them fix.

**Comment by christinechina** [comment]
pls upload for us.

**Comment by kevin-doselection** [comment]
Sure, where is the attachment?

**Comment by christinechina** [comment]
[require.fitment.fix13.xlsx](https://github.com/kevin-doselection/China-Status/files/502155/require.fitment.fix13.xlsx) sorry. resend now.

**Comment by kevin-doselection** [comment]
Got it

**Comment by kevin-doselection** [comment]
which sheet should I take? I saw 1~6 but all missing some data.

**Comment by kevin-doselection** [comment]
Is description_missing_fitment.xlsx also in progress?

**Comment by christinechina** [comment]
hi see sheet 2.  require.fitment.fix13.xlsx

 description will fix today.

**Comment by kevin-doselection** [comment]
These are sku missing year make model
[problem.xlsx](https://github.com/kevin-doselection/China-Status/files/509027/problem.xlsx)

**Comment by christinechina** [comment]
[problem.xlsx](https://github.com/kevin-doselection/China-Status/files/510356/problem.xlsx)
hi kevin, some SKU we can't find database. Pls ask LEO give us database. then we can fix. 
here is that we can fix. 
 description problem will send later,

**Comment by kevin-doselection** [comment]
No problem

**Comment by kevin-doselection** [comment]
Okay, so the data I should use is Sheet1?

**Comment by kevin-doselection** [comment]
Hello, please fix the record with RED cell color
[china.xlsx](https://github.com/kevin-doselection/China-Status/files/520298/china.xlsx)

**Comment by christinechina** [comment]
got it. checking.

**Comment by christinechina** [comment]
pls find the attachment. Some Still highlight in red, thats can't find  data in system. Others are fixed. 
[china.xlsx](https://github.com/kevin-doselection/China-Status/files/532614/china.xlsx)
