### ISSUE TITLE
Model Search Problems

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#32]
@kevin-doselection When searching for the year is "1999" ,brand "Honda", models for the "Civic" and "Rack", the result of "sku" as "CB-SU-4D-202-WS, CB-SU-4D-203- WS, CB-BU-4D-203-WS ", but the search results are not matching. Do you have any idea to solve this problem?

**Comment by kevin-doselection** [comment]
You mean 1999 honda civia shouldn't have  "CB-SU-4D-202-WS, CB-SU-4D-203- WS, CB-BU-4D-203-WS "?

**Comment by DAXIAPI** [comment]
yes,you can check it.fitment did not “1999 honda civia”,also have customer complaints,to search by "1999 honda civic" products do not match.

**Comment by kevin-doselection** [comment]
Check all product's attribute: v_category.
Should be visor rack cargo mat carrier guard, no number anymore

**Comment by kevin-doselection** [comment]
Searching by dropdown list is according to v_category.
Searching by "1999 Honda Civic" is according to the keyword inside the product's attributes.
So if there is an issue that both results are not a match, it is because that the v_category is not correctly setup.
Therefore, you can download the whole product list and update the v_category to the website.

**Comment by DAXIAPI** [comment]
The v_category is correctly setup,three v_category are set to "Rack".The problem is that search "1999 Honda Civic Rack",you can get three product like  "CB-SU-4D-202-WS, CB-SU-4D-203- WS, CB-BU-4D-203-WS ".But it's not matching.
    For example ,SKU as "CB-SU-4D-202-WS"  you can see the fitment (see Italic)"2008-2010 Dodge Avenger,2006-2010 Dodge Charger,2009-2011 Dodge Journey,2005-2008 Dodge Magnum,2007-2011 Ford Edge,2001-2011 Ford Escape,2011 Ford Fiesta,2006 Ford Fusion,2008-2011 Ford Fusion,2000-2007 Ford Taurus,2010-2011 Ford Taurus,2004-2011 GMC Canyon,2010-2011 GMC Terrain,1993 Honda Accord 10th Anniversary Sedan 4-Door,1996 Honda Accord 25th Anniversary Edition Sedan 4-Door,1990-1997 Honda Accord DX Sedan 4-Door,2004-2005 Honda Accord DX Sedan 4-Door,1990-1997 Honda Accord EX Sedan 4-Door,2004-2011 Honda Accord EX Sedan 4-Door,2008-2011 Honda Accord EX-L Sedan 4-Door,1991 Honda Accord EX-R Sedan 4-Door,1995-1997 Honda Accord EX-R Sedan 4-Door,1990-1997 Honda Accord LX Sedan 4-Door,2004-2011 Honda Accord LX Sedan 4-Door,2006 Honda Accord LX Special Edition Sedan 4-Door,2008-2011 Honda Accord LX-P Sedan 4-Door,1991 Honda Accord SE Sedan 4-Door,1993 Honda Accord SE Sedan 4-Door,1997 Honda Accord SE Sedan 4-Door,2007 Honda Accord Special Edition Sedan 4-Door,1996-1997 Honda Accord Value Package Sedan 4-Door,2006-2007 Honda Accord Value Package Sedan 4-Door,_2001-2011 Honda Civic DX Sedan 4-Door,2008-2011 Honda Civic DX-G Sedan 4-Door,2001-2011 Honda Civic EX Sedan 4-Door,2001-2011 Honda Civic GX Sedan 4-Door,2003-2011 Honda Civic Hybrid Sedan 4-Door_
".it's not 1999-Honda-Civic.
      Then we can see a list of product attributes.(year ->"1990;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011")(make->"Dodge;Ford;GMC;Honda")(v_model->"Accord;Avenger;Canyon;Charger;Civic;Edge;Escape;Fiesta;Fusion;Journey;Magnum;Taurus;Terrain")  Obviously,year has 1999,make has Honda,v_model has Civic,and v_category is Rack,so searching by "1999 Honda Civic Rack" you can find SKU as "CB-SU-4D-202-WS".Similarly, you can also  search by "1991 Honda Civic Rack" or "1992 Honda Civic Rack" or 1993 Honda Civic Rack" and many more,according to the different year,can search  "CB-SU-4D-202-WS".You can try your own.
     This is a problem I found,we need to solve this problem.You can think about it.thank!

**Comment by kevin-doselection** [comment]
This is how the extension designed at the first place I believed. 
However, in order to fixes this issue, we might need other solution. I am still looking for another way to display vehicle fitment data in our website.
If we cannot change algorithm for the extension, then we can think how to organize our products to prevent wide range of vehicle fitment in one product.

**Comment by DAXIAPI** [comment]
Yes, I agree with you.I tried the other way and both ran into the same problem.This extension is inherently problematic,so if we can't change algorithm for the extension,do as you said.
