### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#33]
![about_us-after](https://cloud.githubusercontent.com/assets/20631720/18702045/7e6cc44e-8012-11e6-8054-afcd28d1f007.png)
![account-after](https://cloud.githubusercontent.com/assets/20631720/18702049/7e727376-8012-11e6-8ca4-3bd72d8aa926.png)
![appoint-after](https://cloud.githubusercontent.com/assets/20631720/18702058/80b6c2c2-8012-11e6-87aa-ddb70b852767.png)
![contact-after](https://cloud.githubusercontent.com/assets/20631720/18702048/7e70cc6a-8012-11e6-84fb-5da87f7bc03b.png)
![my_order-after](https://cloud.githubusercontent.com/assets/20631720/18702047/7e7032e6-8012-11e6-8643-f139d49f95da.png)
![order-after](https://cloud.githubusercontent.com/assets/20631720/18702046/7e703570-8012-11e6-8d95-3533ca865240.png)
![products-after](https://cloud.githubusercontent.com/assets/20631720/18702051/7eab7dc4-8012-11e6-8ffa-36f2ff062929.png)
![return-after](https://cloud.githubusercontent.com/assets/20631720/18702052/7eacf014-8012-11e6-83c1-23bac3884859.png)
![shop-by-product-after](https://cloud.githubusercontent.com/assets/20631720/18702053/7ead38d0-8012-11e6-847a-0b2b4815a198.png)
![shop-by-vehicle-after](https://cloud.githubusercontent.com/assets/20631720/18702054/7edbcac4-8012-11e6-8815-178cea2f4d80.png)
![terms-after](https://cloud.githubusercontent.com/assets/20631720/18702055/7ee2efca-8012-11e6-9282-f7b93d1771c4.png)
[中文翻译.xlsx](https://github.com/kevin-doselection/China-Status/files/484418/default.xlsx)
see files "中文翻译.xlsx", which have Chinese translation. Please ask the designer to modify the pic,English text ps into Chinese text.thank!

**Comment by DAXIAPI** [comment]
@kevin-doselection The pattern changed to "Video" pattern, "TERMS&SERVICE" text changed to "GUIDE VIDEO" text.thank!
![terms-after](https://cloud.githubusercontent.com/assets/20631720/18700725/605b88d4-800b-11e6-868f-da959d970ffc.png)

**Comment by kevin-doselection** [comment]
Will tell designer ASAP

**Comment by DAXIAPI** [comment]
ok,thank.

**Comment by DAXIAPI** [comment]
hi,kevin,is it in processing now?How long can give me the pictures?

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/77f3vvwfmqxykjh/AADVdfzx9MdfhAQrya3fWuyKa?dl=0

**Comment by kevin-doselection** [comment]
Please close the issue, if no more question here.
