### ISSUE TITLE
Code to every page

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#34]
<script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>

Please add this code to everypage in ltsport.com ( above </body>)

**Comment by kevin-doselection** [comment]
`<script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>`

**Comment by DAXIAPI** [comment]
ok,had done.

**Comment by kevin-doselection** [comment]
Great job.
