### ISSUE TITLE
ltsport.com about-us page modify

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#35]
Hello, please make a design like below for ltsport.com about-us page.
The left column still remain, adjusting the right side to showing trustworthy about our website.
Each details could use one line to explain the description.
Please use HTML design software to make draft first without edit current website.
After the final edition is finish, we would make the update.

[Scan1.PDF](https://github.com/kevin-doselection/China-Status/files/509666/Scan1.PDF)

**Comment by DAXIAPI** [comment]
Is this all right?
![qq 20161005141951](https://cloud.githubusercontent.com/assets/20631720/19103044/15e56700-8b07-11e6-9152-2c6ae2a019d0.png)
![qq 20161005142131](https://cloud.githubusercontent.com/assets/20631720/19103138/9221fc84-8b07-11e6-8f83-d61e73a7feda.png)

**Comment by DAXIAPI** [comment]
[code.docx](https://github.com/kevin-doselection/China-Status/files/510187/code.docx)

**Comment by kevin-doselection** [comment]
1. Can you use icon to replace " VISA Mastercard Amex Discover PayPal Firstdata"?
   like this http://cdn.shopify.com/s/files/1/0070/7032/files/shine-and-shadow.png?118318
2. description change to below

Affordable Auto Accessories with Perfect Fitment
Up-To-Date vehicle information and directly serving U.S.A market.

U.S.A Quality
All-In-One controlling manufacture, shipping and retail activities at Southern California.

SSL 128-Bit AES Encryption and McAfee SECURE
Our site is encrypted by Industry-Standard Security Protocols. 
No Malware or Malicious Links or Phishing Detected context.

Product Protection Insurance with Google Trusted Store
Every order from us is covered by our Product Protection Insurance, also with extra Google's purchase protection for free. 

Reliable Payment Methods: VISA Mastercard Amex Discover PayPal FirstData
By paying with these methods, you keep your credit card information private, meaning that you can shop without worrying about a hacker downloading your account data.

**Comment by kevin-doselection** [comment]
![image](https://cloud.githubusercontent.com/assets/17145866/19122669/6249fcc2-8ae0-11e6-8105-723cc86917fc.png)
Change CONTACT to ABOUT US
Change CONTACT INFO. to OUR STORE

**Comment by DAXIAPI** [comment]
![qq 20161006112107](https://cloud.githubusercontent.com/assets/20631720/19139405/08d909a8-8bb7-11e6-8cde-a531ffd42528.png)

**Comment by DAXIAPI** [comment]
has done

**Comment by kevin-doselection** [comment]
Great. After remove "FedEx...." and "Amazon, ebay....", please update to ltsport.com

**Comment by DAXIAPI** [comment]
has done.
![qq 20161007094608](https://cloud.githubusercontent.com/assets/20631720/19176494/f50c19b2-8c72-11e6-9a30-f77b2c5e0211.png)

**Comment by kevin-doselection** [comment]
Apply these link to each icon
VISA: https://usa.visa.com/
mastercard: https://www.mastercard.us/en-us.html
discover: https://www.discover.com/
Amex: https://www.americanexpress.com/
Paypal: https://www.paypal.com/
Google Trusted store (Text link): https://www.google.com/trustedstores/
SSL 128-bit AES Encryption(Text link): https://en.wikipedia.org/wiki/Transport_Layer_Security
McAfee SECURE( text link): https://www.mcafeesecure.com/
Affordable Auto Accessories(text link): http://www.ltsport.com/products/visor.html

**Comment by DAXIAPI** [comment]
ok,had done.
