### ISSUE TITLE
ltsport.com detail font style

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#36]
Hello,
Please change the font from "Arial" to "Roboto".
If cannot be done, pleaes try "Calibri "

![image](https://cloud.githubusercontent.com/assets/17145866/19121701/417c64fc-8adc-11e6-8bc0-fcd4d568c3bb.png)
![image](https://cloud.githubusercontent.com/assets/17145866/19121704/45669146-8adc-11e6-8a0b-6946a9022477.png)
![image](https://cloud.githubusercontent.com/assets/17145866/19121722/54ce2eb4-8adc-11e6-8b0c-34aa138017ae.png)

**Comment by DAXIAPI** [comment]
"Calibri " is ok,but "Roboto" can't work,I have set "Calibri ".

**Comment by kevin-doselection** [comment]
Doesn't look good. Try to find some font style that is smoother.

**Comment by DAXIAPI** [comment]
Is "Tahoma" ok?
![qq 20161007092458](https://cloud.githubusercontent.com/assets/20631720/19176191/09350e6a-8c70-11e6-9c79-877d7bc15bdd.png)

**Comment by kevin-doselection** [comment]
How about in product detail page?

Sent from my ASUS

-------- Original Message --------

**Comment by DAXIAPI** [comment]
![qq 20161007100544](https://cloud.githubusercontent.com/assets/20631720/19176741/a624d926-8c75-11e6-9276-89ccde220e8a.png)
@kevin-doselection here

**Comment by kevin-doselection** [comment]
Good lets try this one

Sent from my ASUS

-------- Original Message --------

**Comment by DAXIAPI** [comment]
ok

**Comment by kevin-doselection** [comment]
Perfect
