### ISSUE TITLE
GTIN adjustment

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#37]
Hello, 
First, please adjustment all sku to without "-WS" in GS1 DataHub website
URL: https://goo.gl/JXqyH3
Path: Product > Manage > Description > Additional Information > Edit SKU > Save

username: kevin.doselection@gmail.com
password: LIKIsila921

Second, Please fill in gtin code, according from GS1 DataHub website data.
You would be able to export current "in use" record. 
Please DO NOT create new gtin record.

[gtin adjustment.xlsx](https://github.com/kevin-doselection/China-Status/files/514907/gtin.adjustment.xlsx)

Thank you,

Kevin

**Comment by DAXIAPI** [comment]
@kevin-doselection first step is error when I click  "Additional Information".
![qq 20161007101240](https://cloud.githubusercontent.com/assets/20631720/19176878/cb5d7b7a-8c76-11e6-8560-2c2f68cc5642.png)

**Comment by kevin-doselection** [comment]
Maybe try  logout login.

Sent from my ASUS

-------- Original Message --------

**Comment by DAXIAPI** [comment]
I try but it's still error.

**Comment by kevin-doselection** [comment]
I see. However you can login and click product?

Sent from my ASUS

-------- Original Message --------

**Comment by DAXIAPI** [comment]
yes,I can login and click product,but I can't enter “Additional Information”.

**Comment by DAXIAPI** [comment]
[complete gtin.adjustment.xlsx](https://github.com/kevin-doselection/China-Status/files/515174/complete.gtin.adjustment.xlsx)
has fill in gtin code.

**Comment by kevin-doselection** [comment]
No problem, I got this
