### ISSUE TITLE
send us PDF 

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#38]
Hi kevin, 
need PDF of in the list that mark "NEED". pls see attachment for detail. 

Christine
[網站管理PDF .xlsx](https://github.com/kevin-doselection/China-Status/files/521180/PDF.xlsx)

**Comment by kevin-doselection** [comment]
Hello, please take a look. 
[guide.docx](https://github.com/kevin-doselection/China-Status/files/522323/guide.docx)

**Comment by christinechina** [comment]
got it. tks Jess will follow,if any question.
