### ISSUE TITLE
taobao pics

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#40]
hi, kevin. enclosed a excel that tell where need to revised. pls transfer to designer. Then follow untill he send it back. Thanks

[Uploading 淘宝产品图片翻译.xlsx…]()

**Comment by kevin-doselection** [comment]
The file cannot download. Please check it

**Comment by christinechina** [comment]
[淘宝产品图片翻译.xlsx](https://github.com/kevin-doselection/China-Status/files/528696/default.xlsx)
Check again.

**Comment by christinechina** [comment]
Have you received? pls keep check for us. And tell me when designer will finished. Tks.

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/xw8sbd6l0geokqr/AAACC9JUnej02OmFVamOdqrba?dl=0

**Comment by christinechina** [comment]
got it. Other NP. only this one still need revised. 
![image](https://cloud.githubusercontent.com/assets/20959180/19462139/153aead0-951d-11e6-94dd-b87d34f3cb1f.png)

**Comment by christinechina** [comment]
LOGO not good. sizes wrong. 
![qq 20161018131838](https://cloud.githubusercontent.com/assets/20959180/19465289/87cb7386-9535-11e6-9541-259c3a3f6dec.jpg)
![qq 20161018131903](https://cloud.githubusercontent.com/assets/20959180/19465292/8b57635c-9535-11e6-9ccd-6ee0af33ebc9.jpg)
![qq 20161018132011](https://cloud.githubusercontent.com/assets/20959180/19465299/9d2b5de0-9535-11e6-8ffb-f56a66cc0f5f.jpg)

**Comment by kevin-doselection** [comment]
got it

**Comment by kevin-doselection** [comment]
![computer logo](https://cloud.githubusercontent.com/assets/17145866/19528950/df94455e-95e2-11e6-8e53-0e3a789a5db5.jpg)

**Comment by kevin-doselection** [comment]
Hello, I cannot find the issue. Please send us the picture you want us to fix for below objectives.
1. Mobile version caragories pictures update (floor mat, injection visor)
2. computer version Home page pictures

**Comment by christinechina** [comment]
1. floor mat pics, pls ask leo. 
2. computer and mobile version home page requirement. see attachment. 
   [图片修改说明.xlsx](https://github.com/kevin-doselection/China-Status/files/543690/default.xlsx)

**Comment by kevin-doselection** [comment]
1. https://www.dropbox.com/sh/6s6qo150t1co1f1/AADBfcZsrMaRRDeMmu1qw0Oja?dl=0
2. https://www.dropbox.com/sh/uabqsgmrwuz0ddu/AAAAtpro3QkvXCrV1j6m33fVa?dl=0

**Comment by kevin-doselection** [comment]
From Designer: https://www.dropbox.com/sh/f805m1zy9gtxiqh/AABhOmmMFoc714QkUj6leJCQa?dl=0

**Comment by christinechina** [comment]
some of them need revised. see attachment. 
[carpet need pics revised .xlsx](https://github.com/kevin-doselection/China-Status/files/552449/carpet.need.pics.revised.xlsx)

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/dkbrpmwfynu0w3e/AACArQbk0Hhui2Aua3H21RJaa?dl=0

**Comment by christinechina** [comment]
OK.tks
