### ISSUE TITLE
ltsport.com header additional button

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#42]
Hi,
please add 5 button on ltsport.com header, like below
![image](https://cloud.githubusercontent.com/assets/17145866/19330833/995df190-9095-11e6-82b1-33d90cb23b23.png)

About Us: http://www.ltsport.com/about-us
Installation Guide: http://www.ltsport.com/guide?rootId=9
Products: http://www.ltsport.com/products/visor.html
Return: http://www.ltsport.com/return-policy
Shipping: http://www.ltsport.com/shipping-policy
Remove "Support"

**Comment by DAXIAPI** [comment]
![qq 20161013105321](https://cloud.githubusercontent.com/assets/20631720/19335130/6005d644-9133-11e6-95c0-9d4147bffeb5.png)
![qq 20161013105332](https://cloud.githubusercontent.com/assets/20631720/19335133/63fae94c-9133-11e6-8bd6-4696e90098d7.png)
it's this ok?

**Comment by kevin-doselection** [comment]
Looks great. Make sure button and header click event won't effect by each other then do it. And we will see

**Comment by DAXIAPI** [comment]
I tested, it‘s no problem.

**Comment by kevin-doselection** [comment]
1. Remove "Return" and "Shipping", Adding "Replacement.
2. replacement URL: http://www.ltsport.com/replacement
3. Making CMS page "Replacement", with picture and text.
4. Changing "Installation Guide" to "Guide"

![01click_menu](https://cloud.githubusercontent.com/assets/17145866/19903363/969b83c8-a02b-11e6-8f90-9a684ca7a797.png)
![02methods](https://cloud.githubusercontent.com/assets/17145866/19903364/96a057c2-a02b-11e6-85ae-f5077e59aaa0.png)
![03sub_category](https://cloud.githubusercontent.com/assets/17145866/19903365/96afc0ea-a02b-11e6-8a1f-39230d32a69a.png)
![04choose_product](https://cloud.githubusercontent.com/assets/17145866/19903366/96c3421e-a02b-11e6-85ff-835e7f850f84.png)
![05find_part](https://cloud.githubusercontent.com/assets/17145866/19903367/96c53448-a02b-11e6-8213-8f1ad1885e07.png)
![06result](https://cloud.githubusercontent.com/assets/17145866/19903368/96c719fc-a02b-11e6-9f75-352bd977bac4.png)
[instruction.txt](https://github.com/kevin-doselection/China-Status/files/564815/instruction.txt)

**Comment by DAXIAPI** [comment]
@kevin-doselection Someone has finished it.

**Comment by kevin-doselection** [comment]
On 1600*900 the menu will eat over the logo. Can it be fixed?

**Comment by DAXIAPI** [comment]
I have modified.
