### ISSUE TITLE
ltsport.com update pdata and description

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#44]
Update:

About `<br>` and `<br><br>`, please REPLACE it with `<ul> <li></li></ul>` format

![image](https://cloud.githubusercontent.com/assets/17145866/19361871/3454fe3e-9139-11e6-8b3d-60f18d1d65bc.png)
<br>
<br>
Hello, 2 things to update

1 . description (sheet2): For Website and Walmart.com

> 1) Make it short and simple,
>         Every sheet has highlighted record for reference.
> 
> 2) Move "Will fit "year" "make" "model"" to the end of pdata (sheet1). 
> Example: `<br><br>Will Fit ... 
> 
> 3) Use`<b>`name`</b>``<br/>`  for the first line.

Template 1:
![image](https://cloud.githubusercontent.com/assets/17145866/19394100/8129fb5c-91ec-11e6-8e8a-ec0c26be5d65.png)

2 . pdata (sheet1): For Website only

> 1) each record should seperate by `<br>` for line break.
> 
> 2) each group of "MAKE" records should be seperate by `<br><br>` for double line break.
> 
> 3) Contiune from 1.-2), Cut and paste "Will fit "year" "make" "model"" to the end of pdata. 

Template 2: 
![image](https://cloud.githubusercontent.com/assets/17145866/19394126/9cd58920-91ec-11e6-950d-afd1733f92b2.png)

File download:  (including website latest record for each product, and example which is highlight by blue cell background color) 
[descriptionBySku_K.xlsx](https://github.com/kevin-doselection/China-Status/files/528285/descriptionBySku_K.xlsx)

**Comment by christinechina** [comment]
got it.TKS

**Comment by christinechina** [comment]
Hi kevin, 
last time you ask us check description, now finished. pls Mxi it for us.  Then resend the update one to us.  Thanks. 
[description_missing_fitment - 副本.xlsx](https://github.com/kevin-doselection/China-Status/files/528951/description_missing_fitment.-.xlsx)

**Comment by christinechina** [comment]
I send by email too. if you can't  see attachment. pls check email.

**Comment by kevin-doselection** [comment]
Data received and updated.

**Comment by kevin-doselection** [comment]
[updated_description.xlsx](https://github.com/kevin-doselection/China-Status/files/529912/updated_description.xlsx)
This file has latest record of description, based on the file you gave last time.

**Comment by kevin-doselection** [comment]
The first reply in this post is updated. Please take a look.

**Comment by christinechina** [comment]
got it. TKS

**Comment by kevin-doselection** [comment]
Hold the process. Leo has new layout and data arrangement.
Continue at https://github.com/kevin-doselection/China-Status/issues/46
