### ISSUE TITLE
Problem of website we found

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#45]
hi kevin, pls fix the problem in attachment. because jess don't know why some   data imissing, is it  delete by you or not?  Then need you to find out. 
[Website problem.xlsx](https://github.com/kevin-doselection/China-Status/files/529047/Website.problem.xlsx)

**Comment by kevin-doselection** [comment]
Sheet 1: Please help me check in U.S. database, might be some mistake. We need 2004 Honda.
Sheet 2: Fitment and sku combination issue I will forward to Leo

Thanks

**Comment by christinechina** [comment]
hi kevin.  sheet 1:  so that means you haven't del it. OK. Pls check by you side. because jess very busy this period. sorry. 
              Sheet 2: Thank you. if any update, pls let me know.

**Comment by kevin-doselection** [comment]
Sheet 2: Merge both data for combo product.

**Comment by christinechina** [comment]
![image](https://cloud.githubusercontent.com/assets/20959180/19464405/9235c4e0-952e-11e6-898d-379e40c5f200.png)
![image](https://cloud.githubusercontent.com/assets/20959180/19464411/a2e2c54a-952e-11e6-886c-7b8e5a2ff5cf.png)

THE brand model  and year are all different with that in website. So we need fix all by mergen both data in our system????

**Comment by kevin-doselection** [comment]
Just use either one would be fine.

**Comment by christinechina** [comment]
ok.got it.

**Comment by kevin-doselection** [comment]
Let me know if you have any concern.
