### ISSUE TITLE
#2 ltsport.com update pdata and description

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#46]

**Comment by kevin-doselection** [comment]
Layout design:
Specs area: Using website spec.xlsx for each line. And move short_description after it.
Fitment: Using current pdata info from all current product data.xlsx (No data change is needed.)
Description: Using current description info from all current product data.xlsx (No data change is needed.)

[new layout.docx](https://github.com/kevin-doselection/China-Status/files/537083/new.layout.docx)

[all current product data.xlsx](https://github.com/kevin-doselection/China-Status/files/537099/all.current.product.data.xlsx)

[website spec.xlsx](https://github.com/kevin-doselection/China-Status/files/537084/website.spec.xlsx)

**Comment by christinechina** [comment]
got it.  so do you need jess revised now??

**Comment by kevin-doselection** [comment]
Yes, please follow the new design to make layout for product detail page.

**Comment by DAXIAPI** [comment]
![qq 20161020111115](https://cloud.githubusercontent.com/assets/20631720/19545071/f79eb3cc-96b5-11e6-8694-85cb20e8c65c.png)

@kevin-doselection Is this ok?

**Comment by kevin-doselection** [comment]
Good. This is it. 
Base on this layout to design. And Fill in the Specs by following the website spec.xlsx

**Comment by DAXIAPI** [comment]
![image](https://cloud.githubusercontent.com/assets/20631720/19590912/ed241620-97a6-11e6-99cb-6c49834db7e9.png)
ok,had done,please check it.And this is upload file.
https://www.dropbox.com/s/ipo4jpf1tlp2jip/specs.csv?dl=0

**Comment by kevin-doselection** [comment]
Please give me the data name for these column in Magento. So I can create update function.
For example, `pdata`is called `Vehicle Fitment` on Magento backend.
I would need to know `Product Color`, `Type/Style`, `Qty Of Set`, `Surface Finish`, `Dimension`.

**Comment by DAXIAPI** [comment]
@kevin-doselection I have craeted update function.
you can update in http://www.ltsport.com/update/specsUpdate.php.
Color is called product_color on Magento backend.
Type/Style is called type_style  on Magento backend.
Qty of Set is called qty_of_set on Magento backend.
Surface Finish is called surface_finish on Magento backend.
Dimension is called dimension on Magento backend.
And you can see the Magento backend
![qq 20161024090511](https://cloud.githubusercontent.com/assets/20631720/19631066/67a1fde4-99c9-11e6-8982-4877b0de19e5.png)
so you just need to check it.

**Comment by DAXIAPI** [comment]
[website.spec.xlsx](https://github.com/kevin-doselection/China-Status/files/546779/website.spec.xlsx)
just see the highlighted section,I can find the product,pls check it.

**Comment by kevin-doselection** [comment]
Awesome. Confirming, you already updated these data?

**Comment by DAXIAPI** [comment]
yes,I already updated these data,but some product I can find it.so you need to download and chenck hightlighted section,thank.
[website.spec.xlsx](https://github.com/kevin-doselection/China-Status/files/549355/website.spec.xlsx)

**Comment by kevin-doselection** [comment]
Please update these attribute at ltsport.com
Attributes: Height  Width   Depth   Weight  CountryOfOrigin

[update UPC.xlsx](https://github.com/kevin-doselection/China-Status/files/570091/update.UPC.xlsx)

**Comment by DAXIAPI** [comment]
If I need to create new attributes of CountryOfOrigin?This one I do not update it,other I have updated.

**Comment by kevin-doselection** [comment]
Yes 
1. please create new upload for Country Of Origin.
2. create new upload for "categories"
