### ISSUE TITLE
combo data required fill in

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#47]
Hello, another list of combo need data. Please fill it out according to IS record.

Column in needed: year, make, v_model, v_submodel, pdata, description

Data source: 
[website combo need data.xlsx](https://github.com/kevin-doselection/China-Status/files/544899/website.combo.need.data.xlsx)

Reference only: 
[combo need data.xlsx](https://github.com/kevin-doselection/China-Status/files/544900/combo.need.data.xlsx)

**Comment by christinechina** [comment]
Hi kevin, 
SKU is roof rack + soft rack,  not roof rack + basket. PLS double check description and title. Or you need us make similar as that? 

 and  combo  need datat.  I can't see any see anything for reference.  

Sorry, What is  IS record?  I don't understand.

**Comment by kevin-doselection** [comment]
1. website combo need data.xlsx, is the file for fill in data.
2. combo need data.xlsx included every column from ltsport.com, you just need to unhide all column.
3. Please follow the description structure. And yes, make it similar like that.
4. Inventory System record. URL: 107.7.251.90:8080/inventory/

**Comment by christinechina** [comment]
got it. tks.

**Comment by christinechina** [comment]
finished. except N/A
[website.combo.need.data 2.0 10-25.xlsx](https://github.com/kevin-doselection/China-Status/files/552253/website.combo.need.data.2.0.10-25.xlsx)

**Comment by kevin-doselection** [comment]
If use the first sku cannot find fitment data, please use the second sku.

For example:
sku: CB-104-S10,SR-ST-2400-201-WS
Fitment record: CB-104-S10-201 or SR-ST-2400-201

Please make every record has data for listing.

**Comment by christinechina** [comment]
[website.combo.need.data 2.0 11-1.xlsx](https://github.com/kevin-doselection/China-Status/files/563664/website.combo.need.data.2.0.11-1.xlsx)
done!  some can't find data. we have check IS.

**Comment by kevin-doselection** [comment]
Description is like this, please update it.
year, make, v_model looks good

![image](https://cloud.githubusercontent.com/assets/17145866/19898772/ae2bd616-a01a-11e6-8024-d4268898e2d5.png)

**Comment by christinechina** [comment]
OK.
[website.combo.need.data 2.0 11-1.xlsx](https://github.com/kevin-doselection/China-Status/files/565602/website.combo.need.data.2.0.11-1.xlsx)
