### ISSUE TITLE
Magento order by PayPal status set to Complete instead of Processing

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#48]
I noticed that if an order is using PayPal payment, at the end of transaction, it would automatically set the order status to Complete, which should be Processing. Please help me find out what's the issue.

Normal order# 100006667 
![image](https://cloud.githubusercontent.com/assets/17145866/19654826/adcf7184-99ce-11e6-8c8f-5b042e8a8559.png)

Problem order# 100006653 
![image](https://cloud.githubusercontent.com/assets/17145866/19654617/ec1f4fbe-99cd-11e6-9b06-9ec24c4d658e.png)

**Comment by DAXIAPI** [comment]
![1](https://cloud.githubusercontent.com/assets/20631720/20051781/bceeb272-a50b-11e6-9567-c860ce4a72c1.png)
I suspect the problem is here.Can you test it?File address is ‘ltsport.com/html/app/code/local/Mage/Sales/Model/Order.php ’.

**Comment by kevin-doselection** [comment]
Looking at it.
