### ISSUE TITLE
ltsport.com rename product

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#49]
Hello, please help us to rename our products.

Task 1. Rename the product. Please follow the pattern from 2nd attached file.
Task 2. Cut the origin product name and paste to the Description. Make it following at the end of Description record.

> For example,
> Visor: 
> Start with `Dark Smoke Tint`; Brand `LT Sport®`; Style `SunRoof(side)`; Category `Window Visor`; Qty `1(4)pc`; Fitment `For 1990-2014 Jeep`
> 
> Rack (PTU & BU): 
> Start with `Low Profile`; Brand `LT Sport®`; Style `Simple-Load`; Category `Roof Bars`; Qty `2pc`; Fitment `For 2001-2011 Acura MDX/RDX`
> 
> Rack (SPTU & SU): 
> Start with `HeavyDuty`; Brand `LT Sport®`; Style `X-Load`; Category `Roof Bars`; Qty `2pc`; Fitment `For Universal Sedan`
> 
> Splash Guard: 
> Start with `Custom Fit NoMud`; Category `Splash Guard`; Qty `4pc`; Fitment `For 2003-2007 Honda Sedan`
> 
> Car Cover: 
> Start with `LT-Shield Weather-Proof`; Category `Car Cover`; Qty `1pc`; Fitment `For 2005-2008 Cadillac Escalade`
> 
> Bike Carrier: 
> Start with `Trip-Helper Bike`; Bike Amount `3.0(4.0)`; Style `Hitch(Trunk) Mount`; Category `Rack`; Qty `2pc`; Fitment `For 2004-2014 Cadillac`
> 
> Ski Carrier: 
> Start with Brand `LT Sport®`; `Ski 4 Pro` ; Style `Roof Mount`; Category `Carrier`; Qty `2pc`; Fitment `For 1998-2011 Lincoln`
> 
> Kayak Carrier: 
> Start with Brand `LT Sport®`; `Single-Kayak` ; Style `Roof Mount`; Category `Carrier`; Qty `2pc`; Fitment `For 1997-2004 Oldmobile`
> 
> Rubber Mat: 
> Start with Brand `LT Sport®`; `All-Seasoner`; How many row `3.0(1.0)` ; Style `Rubber(Trunk)`; Category `Mats`; Qty `1(5)pc`; Fitment `For 2005-2007 Buick/Isuzu`
> 
> Nylon Carpet: 
> Start with Brand `LT Sport®`; `Top Series`; Style `Nylon Custom Carpet`; Category `Mats`; Qty `4pc`; Fitment `For 2004-2007 Scion xB`
> 
> Storage Bag: 
> Start with Brand `LT Sport®`; `X-Room`; Style `Expandable`; Category `Cargo Bag`; Qty `1pc`; Fitment `For 2001-2016 Acura`
> 
> Cargo Net: 
> Start with Brand `LT-Secure`; `Nylon`; Category `Cargo Net`; Qty `1pc`; Fitment `For Chevy`
> 
> Nylon Carpet: 
> Start with Brand `LT Sport®`;Style `rooftop storage roof rack cargo luggage` ; Category `carrier basket`; Qty `1pc`; Fitment `For 2001-2004 Volvo`

Attachment Area:
Product Data [product data.xlsx](https://github.com/kevin-doselection/China-Status/files/549076/product.data.xlsx)
Example File: sku, name, description, year, make, model, pdata [rename_Product.xlsx](https://github.com/kevin-doselection/China-Status/files/549065/rename_Product.xlsx)

**Comment by christinechina** [comment]
got it.  urgent or not?

**Comment by christinechina** [comment]
Trip-Helper Bike 3.0(4.0) Hitch(Trunk) Mount Rack 2pc For 2004-2014 Cadillac  
bike rack only 1 pc

**Comment by kevin-doselection** [comment]
1. The sooner the better. When could you finish it?
2. This is example template. Should be 1pc.

**Comment by christinechina** [comment]
1. we are very busy this week, and confirm will finished before next firday. and do you want us send us every that we finised or the complete version after finish.  
2. got it.

**Comment by kevin-doselection** [comment]
Send it at once is better.

**Comment by christinechina** [comment]
done!
[rename_Product.xlsx](https://github.com/kevin-doselection/China-Status/files/574794/rename_Product.xlsx)
[product.data 2016-11-7.xlsx](https://github.com/kevin-doselection/China-Status/files/574795/product.data.2016-11-7.xlsx)

**Comment by kevin-doselection** [comment]
Thank!
