### ISSUE TITLE
[Awaiting] need CB-104 video

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#50]
CB-104 translate into chinese video, Please me again. i can't find this record. thanks

**Comment by kevin-doselection** [comment]
Please translate again, since we redo the video last month.
https://www.youtube.com/watch?v=RVj-rY68BT4

**Comment by christinechina** [comment]
hi kevin, 
we need the chinese version. something like this.
![qq 20161027093146](https://cloud.githubusercontent.com/assets/20959180/19750968/4be8e462-9c28-11e6-9673-d1fb6fe13cd5.png)

**Comment by kevin-doselection** [comment]
Do you have the translated subtitle in doc?

**Comment by christinechina** [comment]
no. we don't have. Videos are not translate by us.

**Comment by kevin-doselection** [comment]
Please translate, below is the text file.
[CB-104 guide.txt](https://github.com/kevin-doselection/China-Status/files/562482/CB-104.guide.txt)

**Comment by christinechina** [comment]
104 translation. pls see attachment. And we need CB-902, CB-104,CB-FR installation guide to. it's PDF format. 
[CB-104.guide.txt](https://github.com/kevin-doselection/China-Status/files/563214/CB-104.guide.txt)


[BEICAI SPREADSHEET(1).xlsx](https://github.com/kevin-doselection/China-Status/files/563228/BEICAI.SPREADSHEET.1.xlsx)

**Comment by christinechina** [comment]
104 translation. pls see attachment. And we need CB-902, CB-104,CB-FR installation guide too. it's PDF format. 
[CB-104.guide.txt](https://github.com/kevin-doselection/China-Status/files/563241/CB-104.guide.txt)
[CB-104 Vedio .xlsx](https://github.com/kevin-doselection/China-Status/files/563242/CB-104.Vedio.xlsx)

**Comment by kevin-doselection** [comment]
youtube.com/watch?v=N-nECQ0je_Y

**Comment by christinechina** [comment]
sorry, can't connect with this link. and have you send installation guide PDF format?? we need  CB-902, CB-104,CB-FR. Thanks

**Comment by kevin-doselection** [comment]
From designer: please translate the 2 JPG file so we can make chinese version for you and convert to PDF

![cb-104-s8-guide-vm](https://cloud.githubusercontent.com/assets/17145866/19979900/4c537df4-a1b9-11e6-9e9a-95637d826f55.jpg)
[CB-902-S44-guide-chi.pdf](https://github.com/kevin-doselection/China-Status/files/569797/CB-902-S44-guide-chi.pdf)
![cb-fr-90-vm-guide2](https://cloud.githubusercontent.com/assets/17145866/19979901/4c7ca35a-a1b9-11e6-9f2c-7eed004dec8d.jpg)

**Comment by christinechina** [comment]
where is 902??

**Comment by christinechina** [comment]
[902 &  FR.xlsx](https://github.com/kevin-doselection/China-Status/files/570522/902.FR.xlsx)
done!

**Comment by kevin-doselection** [comment]
[CB-FR-90-guide-chi.pdf](https://github.com/kevin-doselection/China-Status/files/576249/CB-FR-90-guide-chi.pdf)
[CB-104-S8-guide-chi.pdf](https://github.com/kevin-doselection/China-Status/files/576250/CB-104-S8-guide-chi.pdf)

**Comment by christinechina** [comment]
where is 902??

**Comment by christinechina** [comment]
here is some PDF and video need add chinese. pls send to designer. And pls send me 3D floor mat PDF guide. Thanks.

[pdf guide 1.xlsx](https://github.com/kevin-doselection/China-Status/files/580010/pdf.guide.1.xlsx)

**Comment by christinechina** [comment]
[pdf guide 3.xlsx](https://github.com/kevin-doselection/China-Status/files/580018/pdf.guide.3.xlsx)

**Comment by christinechina** [comment]
[pdf guide 2.xlsx](https://github.com/kevin-doselection/China-Status/files/580027/pdf.guide.2.xlsx)

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/oboq0yeu4apc8rd/AAA6u90Iwq2oaWTBCx0GZlsYa?dl=0

**Comment by christinechina** [comment]
got it. missing BR -TAR Viedo, cb-104 video once ready. pls send back to me. 

and below producs need you find PDF for us.. 
1. 3D floor PDF. 
2.  
![image](https://cloud.githubusercontent.com/assets/20959180/20205270/72dc5db0-a812-11e6-89d0-c23ad82e9503.png)

**Comment by christinechina** [comment]
translated more video.  pls send them ba
[翻译.xlsx](https://github.com/kevin-doselection/China-Status/files/585588/default.xlsx)
ck when finished.

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/w10fnjblw0zi4cm/AABqsJu1SlIDiZAYI9kA4-fza?dl=0

the rest are working it, included issue 53 55

**Comment by christinechina** [comment]
hi kevin, PDF all of them not only BR-suv.  sorry. i haven't tell you clearly. 
1. 3 D floor mat PDF 
2.  VSWV-CLIP-ON
3. VSWV-TAPEON
   4.TM Truck mat
4. RCB-505
   6.CB-902-S44
5. CB-HP0308
6. Arm stroage box

**Comment by christinechina** [comment]
[211-6-2016 translation.xlsx](https://github.com/kevin-doselection/China-Status/files/591277/211-6-2016.translation.xlsx)

**Comment by christinechina** [comment]
[BR-4BA.xlsx](https://github.com/kevin-doselection/China-Status/files/618257/BR-4BA.xlsx)
need add chinese PDF. thanks

**Comment by kevin-doselection** [comment]
![br-4ba-vm-guide](https://cloud.githubusercontent.com/assets/17145866/20804891/7cf3b5ea-b7a9-11e6-9ac9-27a5dc645555.jpg)

**Comment by kevin-doselection** [comment]
If no more problem, please close case.

**Comment by christinechina** [comment]
you haven't send me back all i need.

**Comment by kevin-doselection** [comment]
[BR-4BA-VM-guide-chi.pdf](https://github.com/kevin-doselection/951753258/files/634638/BR-4BA-VM-guide-chi.pdf)

**Comment by kevin-doselection** [comment]
If no more problem, please close case.
