### ISSUE TITLE
fix pics

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#51]
Basket in worng position

. pls ask designer fix it. if don't understand, ask leo. tks

![qq 20161026141946](https://cloud.githubusercontent.com/assets/20959180/19715373/4eee0fa8-9b87-11e6-9a81-a4c9a32ec70b.jpg)

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/dkbrpmwfynu0w3e/AACArQbk0Hhui2Aua3H21RJaa?dl=0

**Comment by christinechina** [comment]
OK. TKS.
