### ISSUE TITLE
Urgent alibaba report

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#52]
Hello, 
Since there is more product using our brand name, logo, picture and guide for profit. 
Please using the following account to file a IPR claim(case).

Objective:
1.We need to remove them all to secure our interest. 
2. Gather all buyer and seller info in U.S. and China.

URL: https://ipp.alibabagroup.com
account: kevin.doselection@gmail.com
password: ddd142536

IPR abused item: https://guide.alibaba.com/shop/lt-sport-sn-100000000781-216-for-gmc-top-steel-black-roof-cargo-luggage-carrier-basket_58614864.html

**Comment by christinechina** [comment]
got it. pls help me show attachment to leo.  need you do something, already highlight in yellow. . pls check attachmemt. thanks. 

[商标侵权处理跟进.docx](https://github.com/kevin-doselection/China-Status/files/557877/default.docx)

**Comment by kevin-doselection** [comment]
1.  The sharing process is at domain: https://guide.alibaba.com . However I couldn't find a way to shared product from Amazon to guide.alibaba.com now. Please follow step 4.
2. Did you file the claim at ipp.alibabagroup.com? My account still hasn't complete the identity reg. 
   account: kevin.doselection@gmail.com
   password: ddd142536
3. This is the email to report ipr: ali-guide@service.alibaba.com
   ![image](https://cloud.githubusercontent.com/assets/17145866/19814916/346eb6b8-9cf5-11e6-9ccf-16cc0b5ea7c9.png)
4. Ask our alibaba account manager about how to share product from Amazon
   陆金盈 jinying.lujy@alibaba-inc.com
   ![image](https://cloud.githubusercontent.com/assets/17145866/19815056/e3c7741a-9cf5-11e6-97cd-49589c37c70e.png)

**Comment by christinechina** [comment]
Because, alibaba we have account. no need yours. Regarding customer service guy i have appointment with him today. And the claim will send by our alibaba account.

**Comment by kevin-doselection** [comment]
Good. Keep me updated

**Comment by christinechina** [comment]
![image](https://cloud.githubusercontent.com/assets/20959180/19877754/f3f0d08c-a01c-11e6-9c03-5c38f569a818.png)
done!. they deleted all record that relate to our brand.

**Comment by christinechina** [comment]
![qq 20161101102219](https://cloud.githubusercontent.com/assets/20959180/19877776/17e9a9be-a01d-11e6-8c94-091333c96090.png)

**Comment by christinechina** [comment]
anything need us go on follow up??

**Comment by kevin-doselection** [comment]
Good job, thx
