### ISSUE TITLE
taobao pics new sizes

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#53]
pls send to disigner.  taotbao pics need update. thanks
[尺寸.xlsx](https://github.com/kevin-doselection/China-Status/files/561295/default.xlsx)

**Comment by christinechina** [comment]
have you receive it?

**Comment by christinechina** [comment]
any update for our pics?

**Comment by kevin-doselection** [comment]
From designer: we dont understand your request regarding Tao Bao pics, please fill this list so I will know how many pics you need and the requirement.
[issue 40 pics request list.xlsx](https://github.com/kevin-doselection/China-Status/files/569751/issue.40.pics.request.list.xlsx)

**Comment by christinechina** [comment]
send me back ASAP.
[issue.40.pics.request.list.xlsx](https://github.com/kevin-doselection/China-Status/files/583210/issue.40.pics.request.list.xlsx)

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/rqjewt0azjg8woh/AAAZDacr1CrD2Lvhs3dz8jgXa?dl=0
