### ISSUE TITLE
GS1 Data Hub For Reuse

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#54]
#37

Task1: Change all "For Reuse" item (3266), end date to 11/07/2016
Task2: Change all "For Reuse" item (3266), Update status to Available.

Path: Home > Product > Manage > For Reuse

URL: https://www.gs1us.org/resources/tools/gs1-us-data-hub/product

Guide: https://resources.gs1us.org/DesktopModules/Bring2mind/DMX/Download.aspx?Command=Core_Download&EntryId=3958&language=en-US&PortalId=0&TabId=388

**Comment by christinechina** [comment]
need login? i don't know how to do it? can you explain?

**Comment by kevin-doselection** [comment]
Login username: gzneal@aliyun.com
Password: Leo123456

Here is how to do it. 

For task 1: Go to Home > Product > Manage > For Reuse, editing all " For Reuse" item (3266 records).
Change their end date to 11/10/2016, this can be done one-by-one only.

For task 2: Opening the [guide link ](https://resources.gs1us.org/DesktopModules/Bring2mind/DMX/Download.aspx?Command=Core_Download&EntryId=3958&language=en-US&PortalId=0&TabId=388)  , and follow the 3rd page "For Reuse to Available – Multiple GTINs".
This can be done 100 items at a time.

**Comment by christinechina** [comment]
OK. got it. but got errors.  pls check the pics and reply. 
![1](https://cloud.githubusercontent.com/assets/20959180/20202333/7d17c36e-a7f9-11e6-8f77-608d81fc0d2b.JPG)
![2](https://cloud.githubusercontent.com/assets/20959180/20202335/8150bb84-a7f9-11e6-9852-7693068fb848.JPG)

**Comment by kevin-doselection** [comment]
That is because the date is not today or greater. Just the current date for every time.

**Comment by christinechina** [comment]
OK

**Comment by christinechina** [comment]
not work. stll same errors. pls have a try yoursel and teach me how to do.

**Comment by kevin-doselection** [comment]
1.     Change "Date Available For Reuse" (located below GTIN-12 field) to today and "Save"
2.     Click "Continue" button in Allocation Errors pop-up
3.     Please "enter" reason for recycling this GTIN, "Put for reuse by mistake"
4.     Click on "Make GTIN Available" button (located in between GTIN and GTIN-12 (U.P.C.) fields
5.     Click "Continue" in Available Confirmation

**Comment by kevin-doselection** [comment]
Christin, are you following it?

**Comment by christinechina** [comment]
![image](https://cloud.githubusercontent.com/assets/20959180/21179157/ca5cd0a8-c22d-11e6-858f-3a0ec258fcab.png)
haven't. login but can't find data.

**Comment by kevin-doselection** [comment]
Try this link: https://access.gs1us.org/IdSrv/account/signin?ReturnUrl=%2fIdSrv%2fissue%2fwsfed%3fwa%3dwsignin1.0%26wtrealm%3dhttps%253a%252f%252fmembers.gs1us.org%252f%26wctx%3drm%253d0%2526id%253dpassive%2526ru%253d%25252f%26wct%3d2016-12-14T16%253a43%253a01Z&wa=wsignin1.0&wtrealm=https%3a%2f%2fmembers.gs1us.org%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252f&wct=2016-12-14T16%3a43%3a01Z

![image](https://cloud.githubusercontent.com/assets/17145866/21191311/927155a0-c1d9-11e6-81f7-9de26833df70.png)

**Comment by christinechina** [comment]
[data update end date .xlsx](https://github.com/kevin-doselection/951753258/files/653612/data.update.end.date.xlsx)

i have try to do one sku. pls check attachment and confirm am i do right or not? thanks

**Comment by kevin-doselection** [comment]
That's right.
A way you can check is, the gtin will be searchable in Reuse before you done it.
After you done it, it cannot be searched anymore.

**Comment by christinechina** [comment]
got it. will finish it by early of next week.

**Comment by christinechina** [comment]
![qq 20161226172101](https://cloud.githubusercontent.com/assets/20959180/21479475/be4fe866-cb8f-11e6-8229-f489185e3b99.png)

**Comment by kevin-doselection** [comment]
Fixed, please check.

**Comment by kevin-doselection** [comment]
How's it going?

**Comment by kevin-doselection** [comment]
Please continue to reuse GTIN. Account has been grant permission.

**Comment by christinechina** [comment]
we can't do here. very slow. and got same problem.
