### ISSUE TITLE
[Awaiting] Carpet  advertisement video

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#55]
[Video guide.xlsx](https://github.com/kevin-doselection/China-Status/files/583000/Video.guide.xlsx)
translate done!

Pls send back with chinese.

**Comment by christinechina** [comment]
send me more advertisement video. Thank. for translation

**Comment by kevin-doselection** [comment]
[AD video link.txt](https://github.com/kevin-doselection/951753258/files/625681/AD.video.link.txt)

**Comment by kevin-doselection** [comment]
If no more problem, please close case.
