### ISSUE TITLE
Walmart

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#56]
About walmart order, what do you need from us?

**Comment by kevin-doselection** [comment]
Here is the sample from walmart.com order, please change customer name to "Testing from Walmart.com"
So we can distinct the order from website and walmart.com
[PO_Data_2016-11-11_16-40-43PST.xlsx](https://github.com/kevin-doselection/China-Status/files/586972/PO_Data_2016-11-11_16-40-43PST.xlsx)

**Comment by lihaolihao** [comment]
@kevin-doselection Can you give the sample from Amazon.com order?And how you import Amazon order into ltsport's background,I need to know how it's working,so I need instructions document,pls give me the step of uploading Amazon order  into ltsport's background.thank

**Comment by kevin-doselection** [comment]
Order process: 
Customer placed order: processing
Shipping label created: Completed
