### ISSUE TITLE
pls help to register a facebook /twitter / Pinterest   account

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#58]
account  name :guangzhou neal trading   
 email: gzneal@aliyun.com 
this email password: Leo123456
https://mail.aliyun.com/

**Comment by kevin-doselection** [comment]
Pinterest: gzneal_aliyun
Facebook: gzneal@aliyun.com
Twitter: gzneal@aliyun.com

Password: Leo123456
