### ISSUE TITLE
[Data input] Find sku by make model and create new table

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#59]
Hello,

I need to find each model has what sku and put into different table(example table "honda civic" "honda accord").
Required make and model are in table "design".
Data are in table "Source".

Using filter can find cell contains in 2 column "Vehicle Make" and "Vehicle Model"

[new makemodelissue.xlsx](https://github.com/kevin-doselection/China-Status/files/595897/new.makemodelissue.xlsx)

**Comment by christinechina** [comment]
got it.

**Comment by christinechina** [comment]
![image](https://cloud.githubusercontent.com/assets/20959180/20479955/521c7cc0-b01b-11e6-938a-20f8130e8df1.png)
universail need MADE  only no need match MODEL??

**Comment by kevin-doselection** [comment]
No need for Universal. Just do the 10 Maker's table.

**Comment by christinechina** [comment]
ok

**Comment by christinechina** [comment]
[new.makemodelissue-ford dodge acura.xlsx](https://github.com/kevin-doselection/China-Status/files/615812/new.makemodelissue-ford.dodge.acura.xlsx)
[new.makemodelissue-BMW chevrolet.xlsx](https://github.com/kevin-doselection/China-Status/files/615813/new.makemodelissue-BMW.chevrolet.xlsx)
[new.makemodelissue - toyota Nissan honda.xlsx](https://github.com/kevin-doselection/China-Status/files/615814/new.makemodelissue.-.toyota.Nissan.honda.xlsx)
[new.makemodelissue-lexus GMC.xlsx](https://github.com/kevin-doselection/China-Status/files/615815/new.makemodelissue-lexus.GMC.xlsx)

**Comment by christinechina** [comment]
done
