### ISSUE TITLE
[Taobao design] 12/19 new sku need taobao pics

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#60]
hi kevin upload to taobao. need pics for product page. pls ask designer do it. 
1. car cover for sedan, suv and hatchback
CC-LS
CC-MS
CC-XLS
CC-XXLS

2. soft rack   ST-2400-206-WS  pics and PDF and installation video

3. carpet custom fit pics and PDF and installation video
CP-TCA0711-4D
CP-TP1015-4D
CP-FF0811-4D
CP-HA0812-2D
CP-NA1416-4D

**Comment by christinechina** [comment]
Pls ask designer finish this issues first. thanks

**Comment by kevin-doselection** [comment]
She is working on it.

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/f7ihgckj894u0z0/AACwhVP0B0RC1tRqUWNSFCeQa?dl=0

**Comment by kevin-doselection** [comment]
Hello,
For this website, https://shop157277080.world.taobao.com/
Please give me everything I need to login backend.
For example, username password URL and any instruction, product list, picture file.

**Comment by christinechina** [comment]
https://www.taobao.com/
user name: 里浩车品  PW：Christine487561  
[淘宝开店上架流程.pptx](https://github.com/kevin-doselection/China-Status/files/618089/default.pptx)

**Comment by kevin-doselection** [comment]
CC https://www.dropbox.com/sh/5prf4jlyoz7o37j/AADieYRzrwWv_lXUKiy8V0dxa?dl=0

**Comment by kevin-doselection** [comment]
https://noyoke.world.tmall.com/?spm=a312a.7700718.0.0.MWG1bD
請問我們的淘寶店鋪有辦法做成這樣滿版嗎?

**Comment by christinechina** [comment]
no. 你给的例子是TMALL， 我们不是天猫店做不了这样的效果的。

**Comment by kevin-doselection** [comment]
Got it, can we do like this?
https://shop61304647.world.taobao.com/?spm=a312a.7700824.0.0.d5bHou

**Comment by christinechina** [comment]
now. we already same as this version.

**Comment by kevin-doselection** [comment]
TaoBao store front
please follow the PPT
https://www.dropbox.com/sh/gbh11udbx4bwgh2/AAC5kwGNWmhzGRhX0WiYXmUca?dl=0

**Comment by kevin-doselection** [comment]
TaoBao visor
please follow the PPT
https://www.dropbox.com/sh/km7b9u5f8s7j5qv/AACWf0ZRhBD4SA_2FIMlhmopa?dl=0

**Comment by kevin-doselection** [comment]
Follow by email
