### ISSUE TITLE
ltsport.com Guide background image

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#61]
Hello,
Please fix the missing background image and guide issue.

URL: https://www.ltsport.com/guide
Path: /html/app/design/frontend/default/MAG050058/template/cmspages
File: guide.phtml

1. Background is missing on these page.
https://www.ltsport.com/guide (Homepage of Guide), Carrier (rootId=8304), Cargo (rootId=8554)
2. Guide is missing on these page.
Rack > Soft Pad
Mat > Nylon Carpet

**Comment by DAXIAPI** [comment]
Background is ok,and pls give me some message that I can add the missing page.
pls give me 4 message."name" "video" "description" "pdf".
![qq 20161129100936](https://cloud.githubusercontent.com/assets/20631720/20693824/fb8a3d46-b61b-11e6-91d8-282748e0cfdc.png)

**Comment by kevin-doselection** [comment]
Mat > Nylon Carpet (id: 8566)

> 
>             $name1 = "OEM Floor Mat";
>             $video1 = "ECaeGbxJ21k";
>             $description1 = "OEM Floor Mat.";
>             $pdf1 = "Floor_Mat-VM-_installation_guide1.pdf";
> 

Rack > Soft Pad (id: 8567)

>             $name1 = "Soft Pad for Rooftop Roof Racks";
>             $video1 = "RVj-rY68BT4";
>             $description1 = "Ultra-Light Weight EVA Foam with oxford cloth PVC coating. Adjustable strap wrap pads are designed to wrap around existing roof rack. With a stylish design they provide extra protection in the form of cushioning for both your bar and your kayak/surfboard/etc. Long Lasting & Durable Finish. Suitable for All Weathers.  ";
>             $pdf1 = "SR-ST-2300-guide-VM.jpg";

>             $name2 = "Soft Pad for Rooftop Cross Bars";
>             $video2 = "RVj-rY68BT4";
>             $description2 = "Ultra-Light Weight EVA Foam with oxford cloth PVC coating. Adjustable strap wrap pads are designed to wrap around existing roof rack. With a stylish design they provide extra protection in the form of cushioning for both your bar and your kayak/surfboard/etc. Long Lasting & Durable Finish. Suitable for All Weathers. ";
>             $pdf2 = "SR-ST-2400-guide-VM.jpg";

**Comment by DAXIAPI** [comment]
it's ok.

**Comment by kevin-doselection** [comment]
http://www.ltsport.com/accessories/roofrack.html
background image missing

Please fix it with these picture. 6 categories has each picture.
![cover_rack_bk](https://cloud.githubusercontent.com/assets/17145866/20818136/8b9cacfa-b7e0-11e6-9713-40b18e985235.jpg)
![cover_visor_bk](https://cloud.githubusercontent.com/assets/17145866/20818137/8b9f9082-b7e0-11e6-9041-9d5efe427e0b.jpg)
![cover_cargo_bk](https://cloud.githubusercontent.com/assets/17145866/20818138/8bb134c2-b7e0-11e6-8a88-b6e56a1d5992.jpg)
![cover_carrier_bk](https://cloud.githubusercontent.com/assets/17145866/20818139/8bb64d36-b7e0-11e6-94c3-fe1a6cbf6fdf.jpg)
![cover_guard_bk](https://cloud.githubusercontent.com/assets/17145866/20818141/8bc72d18-b7e0-11e6-983d-ce063b405175.jpg)
![cover_mat_bk](https://cloud.githubusercontent.com/assets/17145866/20818140/8bc65f3c-b7e0-11e6-8b74-d43fc46c05ce.jpg)

**Comment by DAXIAPI** [comment]
It's ok.

**Comment by kevin-doselection** [comment]
Other missing image
id 8545: http://www.ltsport.com/accessories/floormat/trunk-mat.html
id 8563: http://www.ltsport.com/accessories/universalcarrier/universal-bike-carrier/hitch-mount.html
id 8564: http://www.ltsport.com/accessories/universalcarrier/universal-bike-carrier/trunk-mount.html

**Comment by DAXIAPI** [comment]
It's ok.
