### ISSUE TITLE
[U.S. website] Find My Vehicle

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#63]
Objection: Follow up case #59, and create vehicle page
Category: Vehicle Researcher

1. Please create a new button in the menu, Find My Car. And Hide the Replacement it for now.
2-1. Create pages that showing Make.
2-2. Under Make, create pages that showing related Model.
2-3. Under Model, showing products meets the conditions (Make&Model).
3. Create page that showing Universal items.

For all link, using text first. We might have picture for it later.

**Comment by DAXIAPI** [comment]
In processing

**Comment by DAXIAPI** [comment]
www.ltsport.com/researcher
This is the basic function

**Comment by kevin-doselection** [comment]
Is it possible add extra layer?
After Make and Model, Year be there

**Comment by DAXIAPI** [comment]
I try it

**Comment by DAXIAPI** [comment]
Not,do not conform to the logic.

**Comment by lihaolihao** [comment]
I modify the code, please follow up on whether it will affect other orders,thank!

**Comment by kevin-doselection** [comment]
1. Universal accessories is not working.
2. Can you make the result displayed like below, and remove the old one beneath it? Text is hard to find what customer want.
![image](https://cloud.githubusercontent.com/assets/17145866/21107463/aa1e4616-c046-11e6-8ba9-5a0f10302336.png)

**Comment by DAXIAPI** [comment]
ok,like that.
![qq 20161213163344](https://cloud.githubusercontent.com/assets/20631720/21134154/84d93f5c-c157-11e6-9b41-b95fd061da25.png)

**Comment by kevin-doselection** [comment]
1. Universal option is still not working.
2. If "year" cannot use, can you add "v_category"?

**Comment by DAXIAPI** [comment]
1.Because there is no classification under the classification of Universal option,"Select Model" is a sub category of “Select Make”.
![qq 20161214091800](https://cloud.githubusercontent.com/assets/20631720/21166080/4aa5f294-c1de-11e6-9cfa-37dbc75ac13f.png)

**Comment by DAXIAPI** [comment]
2.follow up

**Comment by kevin-doselection** [comment]
1. fixed. Looks great now.

**Comment by kevin-doselection** [comment]
Can you hide this area of product?
![image](https://cloud.githubusercontent.com/assets/17145866/21235454/a83b8ea0-c2ab-11e6-81fe-875d684d3f8c.png)

**Comment by DAXIAPI** [comment]
![qq 20161216085658](https://cloud.githubusercontent.com/assets/20631720/21247851/a6788bfa-c36d-11e6-913c-39a8d7c98d59.png)
like this

**Comment by kevin-doselection** [comment]
Please try a way that makes the text looks clickable and larger
![image](https://cloud.githubusercontent.com/assets/17145866/21552781/d2d96764-cdb8-11e6-9bdd-139c14582bd4.png)

**Comment by DAXIAPI** [comment]
![qq 20161230094425](https://cloud.githubusercontent.com/assets/20631720/21558775/5dcb037a-ce7a-11e6-8b67-55203e0d9480.png)
Is this ok?
