### ISSUE TITLE
[China website ] 12/12 ltsport.net issue

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#65]
logo change, size is not right
		currency $ to CN, now is US dollar
		Header's "service center" and "contact us" is not working in non-homepage, cannot click
		searchbar is not working, cannot search
		origin dropdown list search, v_category value follows the name. example "visor" is "visor", not "9".
		update all product v_category attributes, "9" to visor.
		http://www.ltsport.net/selfdrive, menu too dark cannot see
		website live chat check is working or not
		put every product link to taobao, check all product is showing.

**Comment by kevin-doselection** [comment]
Perform a weekly product update according from ltsport.com

we always have new item

**Comment by DAXIAPI** [comment]
ok,follow up

**Comment by DAXIAPI** [comment]
Do you know how to show others currency,I don't find it.
![qq 20161209172419](https://cloud.githubusercontent.com/assets/20631720/21043928/5fc5b5ea-be34-11e6-8161-aa93e370fd8e.png)

**Comment by kevin-doselection** [comment]
Config. > System > Currency

**Comment by DAXIAPI** [comment]
No, you don't understand what I mean.I want to know why there is only one option "US Dollar".

**Comment by DAXIAPI** [comment]
I can't choose any other currency

**Comment by DAXIAPI** [comment]
![qq 20161212170237](https://cloud.githubusercontent.com/assets/20631720/21093459/f127eb3e-c08c-11e6-8a33-9d8560980f7f.png)

**Comment by DAXIAPI** [comment]
1.Header's "service center" and "contact us" is not need to click.
2.In this page searchbar  is superfluous, has been deleted.
3.logo and selfdrive is ok
4.live chat is ok,using the QQ
5.All products linked to Taobao home page,wait for Taobao product link.

**Comment by kevin-doselection** [comment]
Currency:
![image](https://cloud.githubusercontent.com/assets/17145866/21106898/ad66b6d4-c044-11e6-89fe-e552f49aff3d.png)
![image](https://cloud.githubusercontent.com/assets/17145866/21106932/c2385716-c044-11e6-8e92-884ec09a535f.png)

**Comment by kevin-doselection** [comment]
Good. 
1. Replace "缺貨" & "加到購物車" to "詳情", make every single item showing the same. You can choose to set qty all in_stock or out_of_stock.
2. Product page menu not working. http://www.ltsport.net/products.html
3. menu 车顶行李网 后备箱网 is the same
4. menu 更换零部件 is not working
5. 404 error from http://www.ltsport.net/return-policy. (http://www.ltsport.net/service)

**Comment by kevin-doselection** [comment]
![image](https://cloud.githubusercontent.com/assets/17145866/21152138/feba6bf4-c119-11e6-98dc-899aca2ace72.png)
![image](https://cloud.githubusercontent.com/assets/17145866/21152150/0613c206-c11a-11e6-81bd-d9ee9b5bb116.png)

Please use original size for picture. http://www.ltsport.net/outdoor

**Comment by kevin-doselection** [comment]
1. Menu text change from Bold to Regular.
2. Menu context remove broken-underline.

**Comment by DAXIAPI** [comment]
It's ok.

**Comment by kevin-doselection** [comment]
404 error 
![image](https://cloud.githubusercontent.com/assets/17145866/21191747/ff843e5e-c1da-11e6-91a0-76e337109475.png)

**Comment by kevin-doselection** [comment]
After all done, please update product data by ltsport.com

**Comment by DAXIAPI** [comment]
"404 error" problem is ok.

**Comment by kevin-doselection** [comment]
[product (3).xlsx](https://github.com/kevin-doselection/951753258/files/655649/product.3.xlsx)
After all done, please update product data by ltsport.com

**Comment by kevin-doselection** [comment]
Any updates?

**Comment by DAXIAPI** [comment]
Waiting for translation

**Comment by kevin-doselection** [comment]
Any updates?

**Comment by DAXIAPI** [comment]
yes,in progress

**Comment by kevin-doselection** [comment]
How's it going

**Comment by DAXIAPI** [comment]
It's ok,has done.

**Comment by kevin-doselection** [comment]
Something wrong
![image](https://cloud.githubusercontent.com/assets/17145866/21727791/d252fad6-d3f7-11e6-9640-e8b3eaab73bd.png)

**Comment by DAXIAPI** [comment]
it's ok.
![qq 20170107083744](https://cloud.githubusercontent.com/assets/20631720/21737533/af35ce3a-d4b4-11e6-8594-5d07ae5ce6d2.png)
