### ISSUE TITLE
[US website] update function (qty)

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#66]
1.
URL: ltsport.com/update/qtyUpdate.php
Issue: Trying to update this file, result showing success but upon checking, qty is not updated.
[RNqty.xlsx](https://github.com/kevin-doselection/951753258/files/632105/RNqty.xlsx)

2.
create new import functions, below code might not exact right
please confirm before create
1) country_of_manufacturer
2) manufacturer

**Comment by DAXIAPI** [comment]
1.Trying to update this file,I also have your problem.
2.I have created the new funtions.it also have problem,result showing success but upon checking, qty is not updated.

**Comment by kevin-doselection** [comment]
Using InventoryUpdate.php is fine. Seems like is_in_stock is a must now.
Can you find out the reason?

**Comment by DAXIAPI** [comment]
Follow up
