### ISSUE TITLE
[TaoBao] Review

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#68]
1. [Storefront](https://shop157277080.world.taobao.com/): 
Banner wrong position; 
Done. watermark picture use US version. AD-01 AD-02 AD-03.jpg;

2. [Visor](https://world.taobao.com/item/539563658470.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.12.RqAD1y):
Remove non-exist product. Visor-Main Image-5.jpg;
颜色分类 try using text without picture. Picture is not good to see.
Remove [this item](https://world.taobao.com/item/543014597181.htm) in Visor - [车窗晴雨挡](https://shop157277080.world.taobao.com/category-1270475383.htm?spm=a312a.7700824.w4010-15642987432.8.n0l2r7&search=y&parentCatId=1229563411&parentCatName=%D7%A2%CB%DC%C7%E7%D3%EA%B5%B2&catName=%B3%B5%B4%B0%C7%E7%D3%EA%B5%B2#bd) category.
[天窗晴雨挡](https://shop157277080.world.taobao.com/category-1270478588.htm?spm=a312a.7728556.w4010-15642987421.9.dUuoA6&search=y&parentCatId=1229563411&parentCatName=%D7%A2%CB%DC%C7%E7%D3%EA%B5%B2&catName=%CC%EC%B4%B0%C7%E7%D3%EA%B5%B2#bd) item please double check. It's wrong.

3. [Roof Rack](https://shop157277080.world.taobao.com/category-1229563409.htm?spm=a312a.7700824.w4010-15642987432.10.mkYgcU&search=y&catName=%D0%D0%C0%EE%BC%DC%BA%E1%B8%CB#bd):

-----Please ignore below text-----
 > [一体式纵轨横杆](https://shop157277080.world.taobao.com/category-1263209094.htm?spm=a312a.7700824.w4010-15642987432.11.LRsNRT&search=y&parentCatId=1229563409&parentCatName=%D0%D0%C0%EE%BC%DC%BA%E1%B8%CB&catName=%D2%BB%CC%E5%CA%BD%D7%DD%B9%EC%BA%E1%B8%CB#bd)
> Please use [Product sample](https://world.taobao.com/item/532618777506.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.41.n0l2r7), not [wrong one](https://world.taobao.com/item/532632047279.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.38.n0l2r7)
> We will make better picture in the future.
> [分离式纵轨横杆](https://shop157277080.world.taobao.com/category-1263209095.htm?spm=a312a.7700824.w4010-15642987432.12.LRsNRT&search=y&parentCatId=1229563409&parentCatName=%D0%D0%C0%EE%BC%DC%BA%E1%B8%CB&catName=%B7%D6%C0%EB%CA%BD%D7%DD%B9%EC%BA%E1%B8%CB#bd)
> [无纵轨光顶轨横杆](https://shop157277080.world.taobao.com/category-1270475384.htm?spm=a312a.7700824.w4010-15642987432.13.LRsNRT&search=y&parentCatId=1229563409&parentCatName=%D0%D0%C0%EE%BC%DC%BA%E1%B8%CB&catName=%CE%DE%D7%DD%B9%EC%B9%E2%B6%A5%B9%EC%BA%E1%B8%CB#bd)
> [分离式横杆 2016/11/8 上新](https://shop157277080.world.taobao.com/category-1279350227.htm?spm=a312a.7700824.w4010-15642987432.14.LRsNRT&search=y&parentCatId=1229563409&parentCatName=%D0%D0%C0%EE%BC%DC%BA%E1%B8%CB&catName=%B7%D6%C0%EB%CA%BD%BA%E1%B8%CB+2016%2F11%2F8+%C9%CF%D0%C2#bd)
>
-----Please ignore above text-----

Done Delete these 4 subcategories. Using new defined name: 
縱軌車頂橫桿: CB-902, CB-PTU-H, CB-SPTU-N
裸頂車頂橫桿: CB-104-4D, CB-SU-4D

4. [Mats](https://shop157277080.world.taobao.com/category-1231180125.htm?spm=a312a.7700824.w4010-15642987432.15.vQhPjc&search=y&catName=%C6%FB%B3%B5%BD%C5%B5%E6#bd):
[丝绒环保脚垫](https://shop157277080.world.taobao.com/category-1270478590.htm?spm=a312a.7700824.w4010-15642987432.16.OGkQIb&search=y&parentCatId=1231180125&parentCatName=%C6%FB%B3%B5%BD%C5%B5%E6&catName=%CB%BF%C8%DE%BB%B7%B1%A3%BD%C5%B5%E6#bd) Picture updates: OEM FM pics folder
[全包围脚垫](https://shop157277080.world.taobao.com/category-1270478591.htm?spm=a312a.7700824.w4010-15642987432.17.OGkQIb&search=y&parentCatId=1231180125&parentCatName=%C6%FB%B3%B5%BD%C5%B5%E6&catName=%C8%AB%B0%FC%CE%A7%BD%C5%B5%E6#bd) Is it Combo item? It's empty.
[橡胶汽车脚垫](https://shop157277080.world.taobao.com/category-1270478592.htm?spm=a312a.7700824.w4010-15642987432.18.OGkQIb&search=y&parentCatId=1231180125&parentCatName=%C6%FB%B3%B5%BD%C5%B5%E6&catName=%CF%F0%BD%BA%C6%FB%B3%B5%BD%C5%B5%E6#bd) Please remove old one. Not looking good, and [make a new one](http://www.ltsport.com/accessories/floormat.html)
[后备箱注塑脚垫](https://shop157277080.world.taobao.com/category-1270478593.htm?spm=a312a.7700824.w4010-15642987432.19.OGkQIb&search=y&parentCatId=1231180125&parentCatName=%C6%FB%B3%B5%BD%C5%B5%E6&catName=%BA%F3%B1%B8%CF%E4%D7%A2%CB%DC%BD%C5%B5%E6#bd) It's empty.

5. [Carrier](https://shop157277080.world.taobao.com/category-1270475379.htm?spm=a312a.7700824.w4010-15642987432.20.Kqmj9r&search=y&catName=%B3%B5%B6%A5%B4%EE%D4%D8%BC%DC#bd):
It's empty. 
[皮划艇架](https://shop157277080.world.taobao.com/category-1270475380.htm?spm=a312a.7700824.w4010-15642987432.21.RYD9Pu&search=y&parentCatId=1270475379&parentCatName=%B3%B5%B6%A5%B4%EE%D4%D8%BC%DC&catName=%C6%A4%BB%AE%CD%A7%BC%DC#bd)It's empty. 
[自行车架](https://shop157277080.world.taobao.com/category-1270475381.htm?spm=a312a.7700824.w4010-15642987432.22.Kqmj9r&search=y&parentCatId=1270475379&parentCatName=%B3%B5%B6%A5%B4%EE%D4%D8%BC%DC&catName=%D7%D4%D0%D0%B3%B5%BC%DC#bd) We have[ 2 styles.](http://www.ltsport.com/accessories/universalcarrier/universal-bike-carrier.html)
[雪橇架](https://shop157277080.world.taobao.com/category-1270475382.htm?spm=a312a.7700824.w4010-15642987432.23.Kqmj9r&search=y&parentCatId=1270475379&parentCatName=%B3%B5%B6%A5%B4%EE%D4%D8%BC%DC&catName=%D1%A9%C7%C1%BC%DC#bd) Empty

6. Net:
[车顶行李网](https://world.taobao.com/item/532792823802.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.16.FYxOge) Working on it.

7. [Basket](https://shop157277080.world.taobao.com/category-1231118127.htm?spm=a312a.7700824.w4010-15642987432.25.DNX9db&search=y&catName=%B3%B5%B6%A5%D0%D0%C0%EE%BF%F2#bd):
[车顶行李框](https://item.taobao.com/item.htm?spm=a312a.7700824.w4002-15642987433.32.Dn5dko&id=534274217827) Working on it
8. [Cargo Bag](https://shop157277080.world.taobao.com/category-1276531598.htm?spm=a312a.7700824.w4010-15642987432.26.DNX9db&search=y&catName=%B3%B5%B6%A5%D0%D0%C0%EE%B0%FC#bd):
车顶行李包 It's empty
9. [Car Cover](https://shop157277080.world.taobao.com/category-1233791063.htm?spm=a312a.7700824.w4010-15642987432.27.5024TV&search=y&catName=%C6%FB%B3%B5%B3%B5%D2%C2#bd):
Picture updates in car cover folder.

10. Vehicle Database:
![image](https://cloud.githubusercontent.com/assets/17145866/21205793/06838524-c213-11e6-9e9d-b026df275b9a.png)

File Download: https://www.dropbox.com/sh/b78w4xgpb6i1yt2/AAAZQj3oCI7OLk6jTyzUb7q3a?dl=0

**Comment by christinechina** [comment]
1. already using AD-01 02 03 . 
2. REMOVE.  what's wrong of this two category?
3. 只能做到二级分类，不能再添加三级分类。 所以SKU 分离不能添加。 
4. carpet  pics updated and deleted 全包围脚垫 橡胶汽车脚垫 
5 6 7 8. empty category is because we don't have pics and no producs in stock at all. 
9. CC pic updated.

**Comment by christinechina** [comment]
![cb-104-4d-main image-5](https://cloud.githubusercontent.com/assets/20959180/21221010/af82f4c8-c2f6-11e6-8b8c-724dc41e7e00.jpg)
sizes wrong

**Comment by kevin-doselection** [comment]
Kevin:
For storefront, how about banner?

For Visor, sunroof visor is working on it.


For roof rack, 4 category is too hard for customer to understand which can fit their car. 2 is simple.
For roof rack., Use these sku as product listing in the category. Please make sample product and put the link here. Make sure there isn't non-related product in here.
縱軌車頂橫桿: CB-902, CB-PTU-H, CB-SPTU-N
裸頂車頂橫桿: CB-104-4D, CB-SU-4D

For carrier net basket bag, no problem, we will follow up.

For nylon carpet, thanks.
For rubber carpet and trunk mat, we are working on it.

For car cover., did you changed [Car Cover ](https://world.taobao.com/item/542874108127.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.15.sGbcZm)?

**Comment by christinechina** [comment]
1. fixed
2. right? 
![image](https://cloud.githubusercontent.com/assets/20959180/21255230/8ec9fa10-c3a5-11e6-930f-4d1c3299aa4e.png)
cb-902 https://item.taobao.com/item.htm?id=542580804475
cb-pth-h  https://item.taobao.com/item.htm?id=532555786026
CB-SPTU-N https://item.taobao.com/item.htm?id=539693517564
CB-SU-4D https://item.taobao.com/item.htm?id=541465297135
CB-104 https://item.taobao.com/item.htm?id=532679089078
3. 9 yes. fixed. carcover in chinese means 车衣。

**Comment by christinechina** [comment]
![image](https://cloud.githubusercontent.com/assets/20959180/21255832/4eb36c5a-c3a9-11e6-8516-69975d398be7.png) should be no.4, not 3.

**Comment by christinechina** [comment]
wrong sizes
![cb-104-s8-guide-chi](https://cloud.githubusercontent.com/assets/20959180/21258003/ee5ad8fe-c3b5-11e6-82c8-8f66ea1d2e9a.jpg)

**Comment by kevin-doselection** [comment]
1. Remove [this item](https://world.taobao.com/item/532615256650.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.28.Ao9l2P)from 縱軌 to 無縱軌
2. [Car Cover](https://world.taobao.com/item/542874108127.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.15.sGbcZm) Please use better picture for display image.
3. [Missing detail](https://world.taobao.com/item/539625247498.htm?fromSite=main&spm=a312a.7700824.w4002-15642987433.49.xfzV3U), make sure double every product is looking good and not missing details.
4. Wrong size got it. What size you need?
![taobao-cb-ptu-h-09](https://cloud.githubusercontent.com/assets/17145866/21274865/1fbbf7e8-c37f-11e6-8579-a488ad9e66e9.jpg)

**Comment by kevin-doselection** [comment]
Help me fix this issue.
![image](https://cloud.githubusercontent.com/assets/17145866/21280644/0d25b3b8-c39c-11e6-9386-c1a34d14dd2a.png)

**Comment by christinechina** [comment]
1 2 fixed. 
3.fixed 
4. pls check other producs sizes. i need same. mob version. 
5. here we can't find this issue. pls change another browers to check.

**Comment by christinechina** [comment]
did you change the hyperlink of taobao home page?

**Comment by kevin-doselection** [comment]
Hello, please check 自訂頁面>LT Sport 
URL: https://shop157277080.world.taobao.com/p/rd774290.htm

**Comment by kevin-doselection** [comment]
![cb-104-4d-main image-5a](https://cloud.githubusercontent.com/assets/17145866/21321050/126cda9e-c5c8-11e6-9f2f-a0b57909dcc9.jpg)
![cb-104-guide-chi-1](https://cloud.githubusercontent.com/assets/17145866/21321051/128501b4-c5c8-11e6-9936-9e491d5f173d.jpg)
![cb-104-guide-chi-2](https://cloud.githubusercontent.com/assets/17145866/21321052/1287a522-c5c8-11e6-9fda-747767dc76c2.jpg)

**Comment by christinechina** [comment]
![image](https://cloud.githubusercontent.com/assets/20959180/21379292/dadabd14-c787-11e6-9428-a428146e2618.png)
should link to each categories. for example should link to 注塑晴雨挡 

pls fix

**Comment by christinechina** [comment]
CB-505 product page pics finish? ?

**Comment by kevin-doselection** [comment]
Categories picture is new format. If using old one, the layout will mess up in our end.
So we choose new one with better layout, however sacrifice multiple link.
Since customer has to find out their vehicle, this will avoid the hassle.

**Comment by kevin-doselection** [comment]
All other product page pic are working on it, estimate finished time on Friday.

**Comment by kevin-doselection** [comment]
1.Please start to duplicate finished product. 
Mostly product is Vehicle Make based and using option to put Vehicle Model.

2. Could you explain how do you define the product title? It looks complicate to me.
Also, make sure all kind of product are in TaoBao. You can follow ltsport.net or ltsport.com


Window visor (In-Channel, Tape-On, Sunroof)
注塑晴雨挡: In-Channel, Tape-On
汽车天窗挡: Sunroof

行李架横杆 (Rail, Naked)
縱軌車頂橫桿: PTU: CB-902-S, CB-PTU-H(H54), CB-BTU-H(H54),CB-FR
                        SPTU: CB-SPTU-N(S)(S54)
裸頂車頂橫桿: BU: CB-BU
                        SU: CB-104-4D, CB-SU-4D
Crossbar Soft Pad: SR-ST

汽车脚垫 (Trunk Mat, Rubber Floor Mat, Nylon Carpet)
后备箱垫: FM-UNVS-AR1
橡胶汽车脚垫: FM-UNVS-AR2(AR3)
丝绒环保脚垫: CP-

车顶搭载架 (Bike, Ski, Kayak)
自行车架by Hitch: TR-505, BR-4BA, BR-4BHM
自行车架by Trunk: BR-3BA, BR-SUV
雪橇架: SC-78S
皮划艇架: KR-264, KR-253

汽车车衣
CC-XLP6(XLP7)(XLP8), CC-XXLS(XLS)(LS)(MS), CC-MP8(MP7)(MP6), CC-LP8(LP7)(LP6)

Splash Guard
MG-

Cargo (storage bag, cargo net, basket, basket w/ fairing)
车顶行李包: RB-5233(4233)
车顶行李网: TN-005BLK(004BLK)(003BLK)(002BLK)(001BLK)
车顶行李框: RCB-505
车顶行李框+風擋: RCB-506

**Comment by kevin-doselection** [comment]
New picture
https://www.dropbox.com/sh/rul01on1isa1dh2/AAB4KHshY7waljPpftR9xeIZa?dl=0

**Comment by christinechina** [comment]
got it

**Comment by christinechina** [comment]
how about detail page pics?  yes we are duplicating products.  what's wrong with title?  vehicle model + keyword+ brand+ year+keywords+hot searching words

**Comment by christinechina** [comment]
![qq 20161226200607](https://cloud.githubusercontent.com/assets/20959180/21481813/1474ecac-cba7-11e6-9839-35161e23e133.png)
AD VIDEO  pls  compress into 60‘’。 pls do this job first. and cb-su, carpet, window viosr is most urgent.

**Comment by christinechina** [comment]
![qq 20161226204540](https://cloud.githubusercontent.com/assets/20959180/21482261/6de8a512-cbac-11e6-8c69-5ed9bdf36e7e.png)
WRONG SIZES

**Comment by kevin-doselection** [comment]
Designer: CB-PTU-H pic, the width is 481 same as others, is it too big or too small? What size you want?

**Comment by kevin-doselection** [comment]
[Links.txt](https://github.com/kevin-doselection/951753258/files/674547/Links.txt)
Designer:  We trim all the ADs into 2 clips, please see the txt file to find the links to the videos

**Comment by christinechina** [comment]
[desingner follow.xlsx](https://github.com/kevin-doselection/951753258/files/675313/desingner.follow.xlsx)
vehicel model pics i send via email. too big.

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/qwkmox3qh6su4eb/AADaC8hGyklHB4qBfzEdUCzta?dl=0

**Comment by christinechina** [comment]
hi missing the CB SPTU N part1. that one in attachment is wrong.  pls re send

**Comment by kevin-doselection** [comment]
CB SPTU N
https://www.dropbox.com/sh/9bfe3st08nlcheo/AADjRNlHeLQd5u085gOXHniua?dl=0

**Comment by christinechina** [comment]
i need the 60' video, not pics.

**Comment by christinechina** [comment]
[desingner follow.xlsx](https://github.com/kevin-doselection/951753258/files/680516/desingner.follow.xlsx)


follw by this list. thx.

**Comment by kevin-doselection** [comment]
Designer:  below is CB-SPTU-N part 1, thanks 
https://www.youtube.com/watch?v=tKIkYgCDWfg

**Comment by christinechina** [comment]
got it.  SPTU-S 800*800 PICS  finish?

**Comment by kevin-doselection** [comment]
![cb-sptu-s-main image-1](https://cloud.githubusercontent.com/assets/17145866/21654375/12972a0c-d26a-11e6-8087-a31f452739d4.jpg)
![cb-sptu-s-main image-2](https://cloud.githubusercontent.com/assets/17145866/21654376/129acec8-d26a-11e6-9605-bb6a3462288f.jpg)
![cb-sptu-s-main image-3](https://cloud.githubusercontent.com/assets/17145866/21654377/129ee62a-d26a-11e6-98ed-4e4fbdd821bb.jpg)
![cb-sptu-s-main image-4](https://cloud.githubusercontent.com/assets/17145866/21654378/12b6382a-d26a-11e6-9dbf-0d84a561b50c.jpg)
![cb-sptu-s-main image-5](https://cloud.githubusercontent.com/assets/17145866/21654379/12cefcca-d26a-11e6-9c44-816862b43ce7.jpg)

**Comment by kevin-doselection** [comment]
Are you working on new listing? Please follow the list hiding non-current-exist category and item.
Side Visor 4 item
Rack 9 item
Carpet 5 item
Cover 4 item

**Comment by kevin-doselection** [comment]
Please make sure not to have same duplicated item. 

Visor and carpet for example, HC1215-4D should just have 1 listing with 2012 2013 2014 2015 option.

But rack and cover can have many listing with different sku ending. Depends on how china market prefer
There are 2 options
first, CB-SU-4D-201 for Acura CB-SU-4D-202 for Audi and so on to create different listing
second, CB-SU with multiple option Acura, Audi... in one listing

**Comment by christinechina** [comment]
no. IT'S NOT WORK AT TAOBAO.  they only allow us upload 400 listing.  not thoustand of.  so we cut a lot that duplicate。

**Comment by christinechina** [comment]
Please follow the list hiding non-current-exist category and item.   

sorry i don't understand。

**Comment by kevin-doselection** [comment]
1. got it. let me a list about how do you decide the listing title, option.
2. If you don't have inventory, please remove from the sidebar
![image](https://cloud.githubusercontent.com/assets/17145866/21727818/eac5ad34-d3f7-11e6-86f3-ff5c832662f7.png)

**Comment by christinechina** [comment]
i think no need to del the category. it's for future listing.  and customer will ask if we have o not? we can get  market infor from customer.  if we del it customer will never know about. 
Do you asking about  which SKU belong to which category?

**Comment by christinechina** [comment]
and pls follow the inventory pics progress, we need it.

**Comment by kevin-doselection** [comment]
we can't give you CB-FR-95 for img, video and PDF right now, still seeking vehicle
give me a list what you still need, looks like we gave it all already
also we need "cb-902-s44 (s45) for video, ST-2400 for pdf" translation.

**Comment by christinechina** [comment]
But we have instock. How to do?  CB-FR. I think we can seek together in china. Even finished seeking in USA. We still need to seek again here in china.  vehicels are different. 

and enclosed 902 installation  video and PDF we have already. we need is  the 60' video pls send us then we can translate for you.  

![cb-902](https://cloud.githubusercontent.com/assets/20959180/21797893/a726f99a-d74c-11e6-914c-354823a51f1d.jpg)

ST-2400 Pls send english version for translation.

**Comment by christinechina** [comment]
[desingner follow.xlsx](https://github.com/kevin-doselection/951753258/files/695411/desingner.follow.xlsx)
check the update one. N/A  item

**Comment by kevin-doselection** [comment]
Designer:
CB-902 AD Video is here: https://www.youtube.com/watch?v=PdCQDgpA3fg
CB-PTU-H AD video: 
part1:  https://www.youtube.com/watch?v=lDd4f92DzbM&feature=youtu.be       
part2: https://www.youtube.com/watch?v=pPgavcHRsLA&feature=youtu.be


[SR-ST-2400-guide-VM.pdf](https://github.com/kevin-doselection/951753258/files/696913/SR-ST-2400-guide-VM.pdf)

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/ofom6f0wtezh519/AABIfNhWZ59ihE8mBemX5Igfa?dl=0

**Comment by kevin-doselection** [comment]
1. CNWV-        In Process
2. CB-SU-4D    In Process
3. CB-FR-95-    In Process
4. CP-               https://www.dropbox.com/sh/qwkmox3qh6su4eb/AADaC8hGyklHB4qBfzEdUCzta?dl=0

**Comment by kevin-doselection** [comment]
Designer:
CB-902 AD Chinese part1:  https://youtu.be/8-WNhGhWvbk
                                part2:  https://youtu.be/Qjip0q_oXMY

SR-ST-2400 Guide in Chinese
[SR-ST-2400-guide-chi.pdf](https://github.com/kevin-doselection/951753258/files/702711/SR-ST-2400-guide-chi.pdf)

**Comment by kevin-doselection** [comment]
1. CNWV- 製作中 請暫時用一般Visor 的guide取代
2. CB-SU-4D -製作中 可以先暫時用guide video 取代
3. CB-FR-95- 借到車  下禮拜拍攝
CP- https://www.dropbox.com/sh/qwkmox3qh6su4eb/AADaC8hGyklHB4qBfzEdUCzta?dl=0

**Comment by kevin-doselection** [comment]
1. CNWV- 製作中 請暫時用一般Visor 的guide取代
2. CB-SU-4D -製作中 可以先暫時用guide video 取代
3. CB-FR-95- 借到車 下禮拜拍攝
4. CP- https://www.dropbox.com/sh/qwkmox3qh6su4eb/AADaC8hGyklHB4qBfzEdUCzta?dl=0

**Comment by kevin-doselection** [comment]
Create a new CB-SU listing

Category: 行李架
Packing Image: Get two from your inventory.
Brand: (Fill Best Seller Brand) Find **most popular vehicle make to fill.
Part's category: 汽車配件
Top Basket Material: 鋁合金
Service Included: Skip
Max load: 60 - 70 kgs
Material: 鋁合金
Vehicle Brand: (Fill 100 models) **most popular vehicle make and model to fill.

Title: 通用行李架车顶架 车顶行李架车顶货架 汽车行李架汽車貨架
Selling Point: 
> 1. 三段調整，適用國內外各品牌小型轎車 中型房車 大型貨卡
> 2. 引進美國退款保證政策，確保消費者的權益
> 3. 獨家進口美國，高規高負重A級生產標準
Price: Follow original setting
Options: Use custom color and fill make_model. (Fill 20 models) **most popular vehicle make and model to fill.
Qty: Follow original setting
Purchase Country: China
Display Image: Using these 5 original images we provided. Replace the one only has roof rack with new image* and place at the first.
Display Video: Follow original setting
Description: Follow original setting

*New image: We will give you tomorrow.
**most popular brand: In 2016, According to http://www.autohome.com.cn/guangzhou/

**Comment by kevin-doselection** [comment]
Jess, if Christin is working on TaoBao. Please research what is the shopping method china people used most.
If it's search engine, then started to create index and keyword in our website on it.
If it's shopping channel, keep working on listing improvement.
If social media plays a big role, then take a look at it.

**Comment by kevin-doselection** [comment]
This is CB-FR display img 
![cb-fr-main image-03](https://cloud.githubusercontent.com/assets/17145866/22156999/af0a095e-deea-11e6-9cf4-e7c6b07e8841.jpg)
![cb-fr-main image-05](https://cloud.githubusercontent.com/assets/17145866/22157002/af0ce0ac-deea-11e6-9afa-6ea8ffc32f76.jpg)
![cb-fr-main image-04](https://cloud.githubusercontent.com/assets/17145866/22157000/af0bb844-deea-11e6-8074-c5a96ee85697.jpg)
![cb-fr-main image-01](https://cloud.githubusercontent.com/assets/17145866/22157001/af0c83b4-deea-11e6-8fb4-b300e04b1aa8.jpg)
![cb-fr-main image-02](https://cloud.githubusercontent.com/assets/17145866/22157003/af22e4c4-deea-11e6-80ce-ee8e12166c26.jpg)

**Comment by kevin-doselection** [comment]
Is it only happens on my end?
URL: http://www.ltsport.net/
![image](https://cloud.githubusercontent.com/assets/17145866/22167116/3cc92ec2-df19-11e6-96f5-0b89d71d1d1f.png)

**Comment by christinechina** [comment]
here is update list. We will have chinese new year holiday form 24th jan~ 3th Feb. During this period, pls kee p checking taobao for us and try to finish that still missing. Thanks. 
[desingner follow.xlsx](https://github.com/kevin-doselection/951753258/files/721653/desingner.follow.xlsx)

**Comment by christinechina** [comment]
and above problem fixed.

**Comment by DAXIAPI** [comment]
it's ok
URL: http://www.ltsport.net/
![qq 20170122162529](https://cloud.githubusercontent.com/assets/20631720/22181110/6c362e06-e0bf-11e6-8987-79bc39778ca9.png)

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/05289sy8epdx2wh/AAAOSKXLwuMiV1dZWfeSBCqja?dl=0

**Comment by christinechina** [comment]
![taobao-cb-fr-1](https://cloud.githubusercontent.com/assets/20959180/22616913/1da0945a-eaf3-11e6-909d-b86f6bc2a334.jpg)
can not use  USA flat and 名牌. need revise into  美国品牌 品质保证

**Comment by christinechina** [comment]
[desingner follow.xlsx](https://github.com/kevin-doselection/951753258/files/752124/desingner.follow.xlsx)
pls update

**Comment by kevin-doselection** [comment]
For issue 75 76 77 and taobao, all told designer on 2/6.
But they are working on new item and parts img.
I will follow up until finish.

**Comment by kevin-doselection** [comment]
Please test with these img first, and report about the result
https://www.dropbox.com/sh/sil0j2h8tdcirnq/AACW8T5YHV0H6E_HHtWA4rdna?dl=0

**Comment by kevin-doselection** [comment]
Any updates?
