### ISSUE TITLE
searchbar can't not find the 2002~2007 Honda

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#69]
![qq 20161215171121](https://cloud.githubusercontent.com/assets/20631720/21218008/cce2589a-c2e9-11e6-9f5a-198cd8adae66.png)
Make has no options for Honda when we chose 2005,also I find year about 02~07 that it can't find Honda.ltsport.net is ok,can chose Honda.The searchbar‘s code has not been modified,do you know What has been modified

**Comment by DAXIAPI** [comment]
![qq 20161215172102](https://cloud.githubusercontent.com/assets/20631720/21218285/ec087f46-c2ea-11e6-844f-28abaf633e9a.png)

**Comment by kevin-doselection** [comment]
I can't found why the issue happens. Still looking at it when I having time.

**Comment by kevin-doselection** [comment]
Jess, please fix Guest checkout for ltsport.com
On mobile version (theme:do2)  it's fine, but cannot use on desktop version (theme:MAG)

there are two login page, one is before checkout cart, another is when you type wrong password it will redirect to checkout/onepage/.

**Comment by DAXIAPI** [comment]
1.path:/ltsport.com/html/app/design/frontend/default/MAG050058/template/checkout/onepage
file:link.phtml
this file limits the guest can't checkout,now I hide the restriction code guest can checkout 
![qq 20170111145136](https://cloud.githubusercontent.com/assets/20631720/21838701/7ddd970c-d80e-11e6-9241-e0b933dd069f.png)
2.“_another is when you type wrong password it will redirect to checkout/onepage/._” What is the problem?

**Comment by kevin-doselection** [comment]
Good. Then second issue is customer cannot checkout as guest or register
So I restore the file before the second issue is fixed
![image](https://cloud.githubusercontent.com/assets/17145866/21856317/74abadc8-d7d6-11e6-81cf-066f5dd3b3b3.png)
![image](https://cloud.githubusercontent.com/assets/17145866/21856323/7898f1ca-d7d6-11e6-97de-fbb5db9c2c92.png)

**Comment by DAXIAPI** [comment]
It's ok.
![qq 20170112160631](https://cloud.githubusercontent.com/assets/20631720/21882011/9853c9aa-d8e3-11e6-90a2-00d4997ab327.png)

**Comment by kevin-doselection** [comment]
Please help me fix this issue on tablet
![image](https://cloud.githubusercontent.com/assets/17145866/22002680/b977eb1c-dc02-11e6-9e6b-3680d74668cc.png)

**Comment by kevin-doselection** [comment]
And add this code to footer. I tried on CMS, Configuration>Design>Footer>Miscellaneous HTML.
But it can't stay at the bottom of the page. Keeps stop in the middle.
Failed img:
![image](https://cloud.githubusercontent.com/assets/17145866/22002780/6baf7854-dc03-11e6-87d6-45e0e753fd72.png)

Success Example: https://codepen.io/cbracco/pen/zekgx

**Comment by DAXIAPI** [comment]
this issue is ok.
![qq 20170117100212](https://cloud.githubusercontent.com/assets/20631720/22010843/a0ac0bbc-dcc6-11e6-9aa4-606e6fb75ad4.png)

**Comment by DAXIAPI** [comment]
![qq 20170117104347](https://cloud.githubusercontent.com/assets/20631720/22015377/bedc34d4-dcdc-11e6-83ce-a347bb8a2ce3.png)
![qq 20170117104408](https://cloud.githubusercontent.com/assets/20631720/22015378/bf087de6-dcdc-11e6-9746-d59fec74ab06.png)
Do you have to use the code?

**Comment by kevin-doselection** [comment]
Not necessary if it can be achieved in other way.

**Comment by kevin-doselection** [comment]
Here is updated one. I added more link and picture.
[footer idea.txt](https://github.com/kevin-doselection/951753258/files/712049/footer.idea.txt)

**Comment by DAXIAPI** [comment]
Result is like this.
Home:
![qq 20170118135814](https://cloud.githubusercontent.com/assets/20631720/22054356/2366ec24-dd90-11e6-954e-22251db29520.png)
other page:
![qq 20170118135803](https://cloud.githubusercontent.com/assets/20631720/22054386/453306a8-dd90-11e6-9464-d90f84fcfc06.png)

**Comment by kevin-doselection** [comment]
Please double check on desktop and mobile website
![image](https://cloud.githubusercontent.com/assets/17145866/22156783/b40bc448-dee9-11e6-8e1a-fdbe19024a12.png)

**Comment by DAXIAPI** [comment]
it's ok,mobile website is not suitable, so it not show on the phone.
![qq 20170122145755](https://cloud.githubusercontent.com/assets/20631720/22181076/cb908d02-e0be-11e6-8d6c-313b64851ea7.png)

**Comment by kevin-doselection** [comment]
No problem.

**Comment by DAXIAPI** [comment]
Hi,Kevin,do you find the problem about this issue?
Website about ltsport.com can't find 02~07 Honda.
Where is the problem of product data?

**Comment by kevin-doselection** [comment]
I am working on other project recently. However I would assume the issue is in the database.

**Comment by kevin-doselection** [comment]
1. Please double check mobile version ltsport.com footer. Center the text, make it look better
2. Add Replacement buttom, the one like on desktop version. Also center it, and place below Additional info.

**Comment by lihaolihao** [comment]
1.First question,I can't see the text in the footer.
![qq 20170215095243](https://cloud.githubusercontent.com/assets/20631720/22957636/94b9b174-f364-11e6-814a-5b467a17e751.png)

**Comment by kevin-doselection** [comment]
try it on safari.

Sent from my ASUS

-------- Original Message --------

**Comment by DAXIAPI** [comment]
no,still can't see the text in the footer,can you send me the screenshots of web pages?

**Comment by DAXIAPI** [comment]
I'm test in the ltsport. net, if you think it's ok, then I will do in the ltsport. com
path:http://www.ltsport.net/mobile_home
result:
![qq 20170216151332](https://cloud.githubusercontent.com/assets/20631720/23013261/d6a8e70c-f464-11e6-8a05-3036a67828f4.jpg)

**Comment by kevin-doselection** [comment]
Yes. Totally better than now on mobile devices.
Please apply to ltsport.com mobile version, and double check not affecting desktop footer.

**Comment by DAXIAPI** [comment]
ok,have done and check it.It's not problem,pls confirm,thank.

**Comment by kevin-doselection** [comment]
Please double check what happens.
![image](https://cloud.githubusercontent.com/assets/17145866/23133097/c241fc58-f744-11e6-8e3c-e65bac7c810d.png)

**Comment by DAXIAPI** [comment]
I don't know where your problem is?
I'm here to visit normal.
![qq 20170221084238](https://cloud.githubusercontent.com/assets/20631720/23146458/e68235c4-f811-11e6-8cce-72853a135d86.png)
![qq 20170221084327](https://cloud.githubusercontent.com/assets/20631720/23146456/e60dac5e-f811-11e6-9e2a-0c8864c1de1c.png)

**Comment by kevin-doselection** [comment]
cache.
It's okay now, thx.

**Comment by kevin-doselection** [comment]
Please set footer text to largest without looking bad
now is too small to read

**Comment by DAXIAPI** [comment]
ok
