### ISSUE TITLE
[Walmart API] Product update "price,qty" via php

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#70]
Jess do you know php? We are working on Walmart API to sync our product qty and price in Magento.
API document: https://developer.walmartapis.com/

Single Update Trigger Event: Save in product detail page
![image](https://cloud.githubusercontent.com/assets/17145866/21359359/e74ff9ee-c690-11e6-9ee7-f4ce0c89d07b.png)

Bulk Update Trigger Event: Update action in product list
![image](https://cloud.githubusercontent.com/assets/17145866/21359335/ce6aa85c-c690-11e6-89f7-dbc1e1f08316.png)

FTP Host: ltsport.com Username: ftp@ltsport.com Password: WrensPreysAftersWens27 Port: 21

Path: /ltsport.com/html/app/code/local/Walmart/Api/Model  (for single product update)
File: Observer.php

Path: /ltsport.com/html/app/code/local/Walmart/Api/Model/vendor (for single product update)
File: bilal.php save_w.php

Path: /ltsport.com/html/app/code/local/Magentizer/Bulkupdate/controllers/Adminhtml (bulk update)
File: BulkproductController.php

Web 
URL: https://www.ltsport.com/index.php/admin/ Username: walmartapi Password: walmart123

**Comment by DAXIAPI** [comment]
I read it, so what should I do?

**Comment by kevin-doselection** [comment]
Objective is make update function working.
For now, inventory update is working. However price is not.
We need to find out why the price is not update via bulk function.

**Comment by DAXIAPI** [comment]
ok,follow up.Are you sure inventory updates working?I'm update for single product,but site pages only appear number 12.Last,this problem has recently appeared or has been,pls tell me,thank!

**Comment by DAXIAPI** [comment]
Prompt “Error on saving product walmart:”,connection problems.

**Comment by kevin-doselection** [comment]
Got it. If it shows 12, seems okay. However might just update the qty only not price.

Also, I opened an account for you to check the price and qty in Walmart.com system.

URL: seller.walmart.com
Username: skykevin77@gmail.com
Password: Walmart123!
Path: ITEMS & INVENTORY > Manage Items > Filter "Full sku" (Partial won't work)

**Comment by DAXIAPI** [comment]
no function of saveprice.The code looks a bit confusing.

**Comment by kevin-doselection** [comment]
no wonder. please backup first before editing.
and try to add price into the code.

**Comment by DAXIAPI** [comment]
Method does not work,can you see it?

**Comment by kevin-doselection** [comment]
did you saw the price still not change but qty did in seller.walmart.com?

I know that price not worked. but can you fix it?

**Comment by DAXIAPI** [comment]
I know qty can worked but price not worked.I know that price method is missing,so I write the price mothod but it still not worked,I don't know what the problem is.
 [/ltsport.com/html/app/code/local/Walmart/Api/Model/vendor/fillup/walmart-partner-api-sdk-php/src/Price.php](url)
File: Price.php
This file is not price "update" method,you can check it.

**Comment by kevin-doselection** [comment]
I see. Did you check "uploadAction" event in BulkproductController.php at app/code/local/Magentizer/Bulkupdate/controllers/Adminhtml ? the price is missing, maybe it's the issue.

**Comment by DAXIAPI** [comment]
I know there the price is missing,but the most fundamental reason is the lack of updateprice methods.
look at [/ltsport.com/html/app/code/local/Walmart/Api/Model/vendor/fillup/walmart-partner-api-sdk-php/src/Price.sample.php](url),You will find that there is a lack of "uploadAction" event,so website can't call WAL-MART API,the result is not updated price.You can compare the inventory method at [/ltsport.com/html/app/code/local/Walmart/Api/Model/vendor/fillup/walmart-partner-api-sdk-php/src/inventory.php](url)
I tried many times but failed. Look at the following figure, this is my own added code, code comparison of the inventory method, and now the problem appears in the red circle where I do not know how to add, can not understand the original author's intention. So this is the problem to be solved.
![qq 20170105172235](https://cloud.githubusercontent.com/assets/20631720/21675316/6336fa84-d36c-11e6-9664-5c9dd8caec76.png)

**Comment by kevin-doselection** [comment]
Please try to check another way.
Path: /ltsport.com/html/app/code/local/Magentizer/Bulkupdate
They said single product update and bulk update are different.

**Comment by DAXIAPI** [comment]
still not worked.
![qq 20170106175925](https://cloud.githubusercontent.com/assets/20631720/21714439/ed5d2206-d439-11e6-9f77-d81d723b3962.png)

**Comment by kevin-doselection** [comment]
Pause this issue first
