### ISSUE TITLE
ltsport.com new update method: reviewcount reviewvalue

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#71]
Please create a new update method for two attributes.
And after created, please assign all product random value between below range.
reviewcount: 0 - 1000 (number)
reviewvalue: 3.0 - 5.0 (number)

**Comment by lihaolihao** [comment]
what's this?Please say clearly,thank.

**Comment by DAXIAPI** [comment]
OK,now I understand.

**Comment by DAXIAPI** [comment]
it's ok.
