### ISSUE TITLE
Web site navigation bar can not drop

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#73]
![qq 20170102094715](https://cloud.githubusercontent.com/assets/20631720/21584050/1d9a4b2e-d0d4-11e6-8d50-27f9c5b1d35a.png)
![qq 20170102101537](https://cloud.githubusercontent.com/assets/20631720/21584064/85952ff0-d0d4-11e6-92c3-6d05ecb36cdc.png)
Today, I found that the background of the site without a drop-down box, JS loading error. Is this a problem when you visit? If so, please check the reasons, thank you.

**Comment by kevin-doselection** [comment]
why are you opening the case?
is this china website?
where did you saw the dropdown box not working?
