### ISSUE TITLE
CB-SU

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#75]
Create a new CB-SU listing

Category: 行李架
Packing Image: Get two from your inventory.
Brand: (Fill Best Seller Brand) Find **most popular vehicle make to fill.
Part's category: 汽車配件
Top Basket Material: 鋁合金
Service Included: Skip
Max load: 60 - 70 kgs
Material: 鋁合金
Vehicle Brand: (Fill 100 models) **most popular vehicle make and model to fill.

Title: 通用行李架车顶架 车顶行李架车顶货架 汽车行李架汽車貨架
Selling Point: 
> 1. 三段調整，適用國內外各品牌小型轎車 中型房車 大型貨卡
> 2. 引進美國退款保證政策，確保消費者的權益
> 3. 獨家進口美國，高規高負重A級生產標準
Price: Follow original setting
Options: Use custom color and fill make_model. (Fill 20 models) **most popular vehicle make and model to fill.
Qty: Follow original setting
Purchase Country: China
Display Image: Using these 5 original images we provided. Replace the one only has roof rack with new image* and place at the first.
Display Video: Follow original setting
Description: Follow original setting

*New image: We will give you tomorrow.
**most popular brand: In 2016, According to http://www.autohome.com.cn/guangzhou/

**Comment by christinechina** [comment]
LISTED

**Comment by kevin-doselection** [comment]
Seems like keyword is not the only factor that affects the ranking.
You have other idea to boost it without large cost?

**Comment by DAXIAPI** [comment]
path:https://www.dropbox.com/s/nydo66gqjl40wnz/CB-SU%E8%AF%A6%E6%83%85%E9%A1%B5%E5%9B%BE%E7%89%87%E8%AE%BE%E8%AE%A1%E8%A6%81%E6%B1%82.xlsx?dl=0

**Comment by DAXIAPI** [comment]
Hi,Kevin,Taobao product display page can help the ranking.Now CB-SU need new picture show to customers.I have already written the picture design requirements.Please download the file,and ask designer to  design picture.

**Comment by kevin-doselection** [comment]
For issue 75 76 77 and taobao, all told designer on 2/6.
But they are working on new item and parts img.
I will follow up until finish.

**Comment by kevin-doselection** [comment]
From Designer:
What size for the pics for CB-SU? Thanks
I will start doing those pics soon

**Comment by DAXIAPI** [comment]
width:750px,but height is not limited.

**Comment by kevin-doselection** [comment]
![taobao-su-4d-13](https://cloud.githubusercontent.com/assets/17145866/22946271/c7f3b5bc-f2ab-11e6-829a-1f0b7357ada5.jpg)
![taobao-su-4d-14](https://cloud.githubusercontent.com/assets/17145866/22946270/c7f2ce22-f2ab-11e6-87d5-d866c0e82251.jpg)
![taobao-su-4d-12](https://cloud.githubusercontent.com/assets/17145866/22946269/c7efeda6-f2ab-11e6-8995-4ae60f1a381e.jpg)

**Comment by DAXIAPI** [comment]
ok,thank.

**Comment by kevin-doselection** [comment]
If no more issue on this case, please close it. Thanks
