### ISSUE TITLE
company introduction page 

### ISSUE THREAD

**Issue by christinechina** [kevin-doselection/951753258#76]
Hi kevin, pls ask designer design a  page that  intrduction our US company for taobao.  enclosed some information。。
[品牌故事1.xlsx](https://github.com/kevin-doselection/951753258/files/704015/1.xlsx)

**Comment by kevin-doselection** [comment]
Working on it, please tell us the width x height, size and img format.

**Comment by DAXIAPI** [comment]
![qq 20170116145508](https://cloud.githubusercontent.com/assets/20631720/21973469/db607eee-dbfb-11e6-966d-262c2e589f12.png)

**Comment by DAXIAPI** [comment]
Have designer done the page?

**Comment by DAXIAPI** [comment]
Please ask the designer to follow up,thank.

**Comment by kevin-doselection** [comment]
For issue 75 76 77 and taobao, all told designer on 2/6.
But they are working on new item and parts img.
I will follow up until finish.

**Comment by DAXIAPI** [comment]
ok,thank.

**Comment by lihaolihao** [comment]
ok,thank.

**Comment by kevin-doselection** [comment]
![1](https://cloud.githubusercontent.com/assets/17145866/22993044/67bed52a-f376-11e6-98e7-c60cfd908e68.jpg)
![2](https://cloud.githubusercontent.com/assets/17145866/22993042/6795ae52-f376-11e6-9efd-f6df089965d9.jpg)
![3](https://cloud.githubusercontent.com/assets/17145866/22993043/679f73a6-f376-11e6-9db2-c77954758406.jpg)

**Comment by DAXIAPI** [comment]
ok,thank.

**Comment by kevin-doselection** [comment]
If no more issue on this case, please close it. Thanks
