### ISSUE TITLE
淘寶無線端商品詳情頁

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#77]
現在淘寶無線端商品詳情頁圖片出現模糊情況，需要重新設計圖片。
要求：
1.尺寸：寬：608px，高：不超過920px
2.所有圖片總佔用空間：不超過2056k
3.使用高分辨率
4.導出圖片格式為JPG

下圖是出現模糊情況的分析：
![qq 20170118171147](https://cloud.githubusercontent.com/assets/20631720/22058059/86d083e4-dda2-11e6-9510-2b7228a7a9f0.png)

**Comment by Doselectioninc** [comment]
Hi all
Please assign to our designer fix it. After they finish CB-FR installation guide and ads

Sent from my iPhone

On Jan 18, 2017, at 1:19 AM, Jsee <notifications@github.com<mailto:notifications@github.com>> wrote:


$B8=:_EqUoL5@~C<>&IJ>\>pJGT&JR=P8=LO8R>p67!$<{MW=E?7@_7WT&JR!#(B
$BMW5a!'(B
1.$B<\@#!'yn!'(B608px$B!$9b!'ITD62a(B920px
2.$B=jM-T&JReA(B?$BMQ6u4V!'ITD62a(B2056k
3.$B;HMQ9bJ,Q~N((B
4.$BF3=PT&JR3J<00Y(BJPG

-

**Comment by DAXIAPI** [comment]
Where is the designer? I didn't find him.
![qq 20170119084407](https://cloud.githubusercontent.com/assets/20631720/22089048/83c2f64c-de23-11e6-9e40-941267e816e7.png)

**Comment by Doselectioninc** [comment]
I will ask them join it

Sent from my iPhone

On Jan 18, 2017, at 4:45 PM, Jsee <notifications@github.com<mailto:notifications@github.com>> wrote:


Where is the designer? I didn't find him.
[qq 20170119084407]<https://cloud.githubusercontent.com/assets/20631720/22089048/83c2f64c-de23-11e6-9e40-941267e816e7.png>

-

**Comment by DAXIAPI** [comment]
ok,thank.

**Comment by kevin-doselection** [comment]
Please give us a file included
1. link, where you see it's unclear
2. img origin files
then we can investigate what is the issue and have the material to work with

**Comment by DAXIAPI** [comment]
All product details page are blurred,you can see in the phone.
In the below,I intercepted the pictures when browsing in the phone.
![qq 20170204143604](https://cloud.githubusercontent.com/assets/20631720/22616489/e2725b98-eae8-11e6-9d40-c49a9ff6a294.png)
![qq 20170204143632](https://cloud.githubusercontent.com/assets/20631720/22616490/e27684ac-eae8-11e6-8640-96e43056a1f3.png)
![qq 20170204144004](https://cloud.githubusercontent.com/assets/20631720/22616491/e2d35560-eae8-11e6-9dd5-14f8e5188fb3.jpg)

**Comment by DAXIAPI** [comment]
Now we need to solve the problem.At first,we can solve CB-PTU CB-SPTU and Window Visors .
Picture size----height:608px;  width;900px

**Comment by DAXIAPI** [comment]
Please ask the designer to follow up,thank.

**Comment by DAXIAPI** [comment]
![qq 20170204160853](https://cloud.githubusercontent.com/assets/20631720/22616975/59e8465a-eaf4-11e6-8d25-338b82a99cb3.png)
The right size will look clear

**Comment by DAXIAPI** [comment]
And about fonts, please use the phone font,thank.

**Comment by kevin-doselection** [comment]
For issue 75 76 77 and taobao, all told designer on 2/6.
But they are working on new item and parts img.
I will follow up until finish.

**Comment by christinechina** [comment]
pls send me CB-SU psd FORMAT. PSD format. Thx.  urgent

**Comment by kevin-doselection** [comment]
@christinechina We need to know what file you need (display img, detail img, install PDF guide), why you need it and where are you going to use it. Because Leo did let us release some img for China, but some img that he prefers remain the origin design style, so we cannot release it.
I will contact to Leo as soon as I got your reply, thx.

**Comment by christinechina** [comment]
Dear all, first of all we need to change into a new style that to meet chinese flavoru. as you can see by the  data below. jump rate is 78%.  
Vister qty is growing but jump rate haven't lower. It's not match. So i think product page have someting wrong. we need improve it. 
and you at the 18th Feb, we upload the there new pics of cu-su. the jump rate become lower, but still high. and you can see the small change by the  chart.  customer only stay at this page 24-37'.   most of our customer visit taobao via mobile. That means they can only see there pics. Then go away.  if under wifi, customer can go through the product page within 30'. but i think can't find any interesting.  

![image](https://cloud.githubusercontent.com/assets/20959180/23197055/8e9e661a-f8f8-11e6-95cb-a58ec3646fd2.png)
![04824d5d438fc44c1d75b312a8c80de8](https://cloud.githubusercontent.com/assets/20959180/23197108/e256e390-f8f8-11e6-97d1-3eb720ce00f5.png)
![qq 20170222122124](https://cloud.githubusercontent.com/assets/20959180/23197226/c28928e2-f8f9-11e6-9247-9d418ed616c3.jpg)

**Comment by christinechina** [comment]
here is some good selling seller  
https://detail.tmall.com/item.htm?spm=a230r.1.14.6.F1Ycw6&id=40957817743&cm_id=140105335569ed55e27b&abbucket=6


https://detail.tmall.com/item.htm?spm=a1z10.3-b-s.w4011-15220725410.56.bEoaze&id=42955049965&rn=061c9ba6a53092c881d0ca12fbcd230a&abbucket=4&skuId=90698580099

**Comment by christinechina** [comment]
it's really hard to tell designer how to do and what chinese like.  we are not asking do the same as these seller. but at lease what they have , we must have.   so we want to try to do our own page.   so pls help to explain for us. thanks.

**Comment by kevin-doselection** [comment]
We will have a meeting today and update asap

**Comment by kevin-doselection** [comment]
leo accept the concept that you want our ad goes like china style.
however he prefer maintains high-quality, USA and clean.
designer will gives you another type of details image in product page. trying to make it colorful meanwhile not losing high class feeling.
about usa factor, we will take as many usa background as we could, either in video or image.
the less photoshop the better it feels real. 
these are the ideas we come up with.

**Comment by christinechina** [comment]
got it. thx.
