### ISSUE TITLE
[ltsport.com] new attribute: bestseller_custom

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#78]
Attribute name: bestseller_custom

Required: update method.

**Comment by DAXIAPI** [comment]
it's ok.
path:http://www.ltsport.com/update/bscustomUpdate.php
![qq 20170204102404](https://cloud.githubusercontent.com/assets/20631720/22614892/2580d182-eac4-11e6-8f77-a0db97cda278.png)

**Comment by kevin-doselection** [comment]
Add another upload function: 
_links_related_sku               _links_related_position                     _links_crosssell_sku                  _links_crosssell_position
and test it with one product, see is it safe to use.

**Comment by DAXIAPI** [comment]
update path:www.ltsport.com/update/linksUpdate.php
Attribute name:links_related_sku  links_related_position  links_crosssell_sku  links_crosssell_position
test product sku:VSWV-CRUZE1516-4D-201-WS
test result:
![qq 20170213094024](https://cloud.githubusercontent.com/assets/20631720/22868425/c17a4952-f1d0-11e6-93fe-a8eecaa152a6.png)

**Comment by kevin-doselection** [comment]
Thanks
