### ISSUE TITLE
[ltsport.com ltsport.net] vehicle database update to 2017

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#80]
Please duplicate 2015 vehicle and change to 2016 and 2017 on both database.

Server: localhost »Database: ltsportc_magento »Table: year_make_model_submodel_master
![image](https://cloud.githubusercontent.com/assets/17145866/22892340/0f649f8c-f1c7-11e6-999b-88a376509a54.png)

**Comment by DAXIAPI** [comment]
chang 2015 to 2016 and 2017?

**Comment by DAXIAPI** [comment]
path:https://www.dropbox.com/sh/fzo3xik3wlvz9b2/AAAkGjAlJT9qrVEhbOfB4JTka?dl=0
this file update for ltsport.com

**Comment by DAXIAPI** [comment]
path:https://www.dropbox.com/sh/56zdglb8rdygjex/AACg-c57JuRiyg8P2J6_Dzzqa?dl=0
this file update for ltsport.net

**Comment by DAXIAPI** [comment]
And I've uploaded the data.

**Comment by kevin-doselection** [comment]
Duplicate 2015 and change to 2016&2017

So it will has 2015; 2016; 2017 in database

please don't missing 2015 data while creating 2016 2017

**Comment by DAXIAPI** [comment]
yes,I see and I have done,plese check it,thank.

**Comment by kevin-doselection** [comment]
Thanks. Please add 2016 2017 on the dropdown list too.
![image](https://cloud.githubusercontent.com/assets/17145866/23073445/6cda01f4-f4ea-11e6-8ac4-01a8518eeee0.png)

**Comment by DAXIAPI** [comment]
got it,already finish.
