### ISSUE TITLE
[ltsport.com] v_category dropdown option

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#82]
please change v_category option to below, apply to both desktop and mobile version

Search All Category
-----------------------
side window visor
sunroof visor
-----------------------
roof rack
roof rack wrap pad
roof basket
ski carrier
kayak carrier
-----------------------
hitch cargo basket
trunk bike carrier
hitch bike carrier
-----------------------
cargo bag
cargo net
-----------------------
car cover
splash guard
-----------------------
rubber mats
custom nylon mats
trunk mats
-----------------------

when you finished it. please update v_category by the link and CSV file
http://www.ltsport.com/update/v_categoryUpdate.php
* please save as CSV file before upload

[v_category.xlsx](https://github.com/kevin-doselection/951753258/files/775498/v_category.xlsx)

**Comment by DAXIAPI** [comment]
ok,have done,pls check it,thank.

**Comment by DAXIAPI** [comment]
![qq 20170215171641](https://cloud.githubusercontent.com/assets/20631720/22968034/d50a6540-f3a3-11e6-9e15-d708c3ee7135.png)

**Comment by kevin-doselection** [comment]
Thanks. Got it.
1. Search all category has issue. Better adjust the code to "v_category=" with no search criteria.
2. Is it possible to change "side window visor" to "Side Window Visor" and still can search?
3. Please also apply to catalogsearch/result 's dropdown list.
Link: http://www.ltsport.com/catalogsearch/result/?q=2014+acura+mdx+visor&x=0&y=0
![image](https://cloud.githubusercontent.com/assets/17145866/23073251/b85b3414-f4e9-11e6-8803-4a9502b370ba.png)
