### ISSUE TITLE
[youtube] new video

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#87]
https://www.youtube.com/watch?v=HqoACVIYtlE
https://www.youtube.com/watch?v=IbrH4n22rEg
https://www.youtube.com/watch?v=QLTC40CG2pU
https://www.youtube.com/watch?v=iLsIwwT68rc
https://www.youtube.com/watch?v=bjLIyFHhGLY
https://www.youtube.com/watch?v=9CBHzGU4lwA

**Comment by kevin-doselection** [comment]
TaoBao CB-SU-4D resize 750

https://www.dropbox.com/sh/5i8q56w9ak032hm/AAAENyo2m0FSc-24w-cfTL68a?dl=0

**Comment by christinechina** [comment]
need translation?

**Comment by christinechina** [comment]
CB-SU send  us PSD format. some chinese we need to revised.  no need designer do. we can do it ourself. Thanks.

**Comment by christinechina** [comment]
cb-su sizes still wrong.  and you send me a old version.  pls double check. and send me PSD version to save more time.

**Comment by DAXIAPI** [comment]
Hi,kevin,video translation is complete, please download the file,thank.
链接：http://pan.baidu.com/s/1nvJj0Xr 密码：m6nf

**Comment by kevin-doselection** [comment]
hi, CNWV is done, below is the link:
part 1  https://www.youtube.com/watch?v=T24SWiqH98w
par t2  https://www.youtube.com/watch?v=ZhTZTTglIz4

**Comment by kevin-doselection** [comment]
Anything else you need from designer?

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/f7x34su4m17yv58/AAD9EAR2dnpW6joFqWxrsTCha?dl=0

the rest will be done on friday

**Comment by christinechina** [comment]
i need cb-btu. not cb-bu.  othes no need to to do  now.

**Comment by christinechina** [comment]
pls send pics by email directly.  and pics siezs still wrong.    
1、pc端尺寸宽度是750*高，切图时，一张图片的高度不超过960像素
2、手机端尺寸宽度是620*高，切图时，一张图片的高度不超过960像素
3、手机端中文字体用到25个点以上，整个详情页图片不超过25张图即可，可根据排版适当调整高度

**Comment by kevin-doselection** [comment]
Hi, please fill this form so we will know which SKU you guys want.
[Request SKU Tao Bao pics.xlsx](https://github.com/kevin-doselection/951753258/files/914827/Request.SKU.Tao.Bao.pics.xlsx)

**Comment by christinechina** [comment]
CB-SU， CB-902, CB-FR 。 摄影的原图。 其他暂时不需要。
