### ISSUE TITLE
[ltsport.com] custom option

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#88]
Path: Product > Custom Options
SKU: MG-TCA0711-4D-201-WS

1. Make custom option can be shown on frontend
2. Create import function to update product's custom option (title and context)

DB: ltsportc_magento 
DB 1: 
catalog_product_option
Column: 
option_id (unique), product_id (item# e.g. 679), type (drop_down), is_require (1), sort_order 

DB 2: 
catalog_product_option_title
Column: 
option_title_id (unique), option_id (foreign key), store_id (0), title (year make model body type)

DB 3: 
catalog_product_option_type_price
Column: 
option_type_price_id (unique), option_type_id, store_id (0), price (0), price_type (fixed)

DB 4: 
catalog_product_option_type_title
Column: 
option_type_title_id (unique), option_type_id (foreign key), store_id (0), title (coupe sedan camry toyota 2007 2008 2009 2010 2011)

DB 5: 
catalog_product_option_type_value
Column: 
option_type_id (unique), option_id (foreign), sort_order (0)

**Comment by DAXIAPI** [comment]
1.I don't understand what ‘custom option’ is,and what do you want?
2.Is this the database you created?

**Comment by kevin-doselection** [comment]
I need your idea

For now, customer having issue to find out that is the product fits their car.
Even we gave them the list, it still not convenient for them.
![image](https://cloud.githubusercontent.com/assets/17145866/24715688/3da0e512-19e1-11e7-9353-c5bc1f7ecdc9.png)

Is it possible to use the dropdown list like this after SKU area?
![image](https://cloud.githubusercontent.com/assets/17145866/24715771/82cbb7ca-19e1-11e7-9807-c40844085f0f.png)
I am thinking 
1) using product's attribute: year, make, v_model, v_submodel to show only this product's year make model submodel
or
2) showing all year make model submodel with a Check My Car button, after click, compare with product's year make model submodel and shows up a result (It fits your car; It doesn't fit your car)




-------------- ignore below for now ----------

> 1. custon options is an attribute exists in simple product.
> Check on SKU: MG-TCA0711-4D-201-WS
> This is how backend looks. You can set value here.
> ![image](https://cloud.githubusercontent.com/assets/17145866/24713800/81c58aa0-19db-11e7-9c39-4626d8b62001.png)
> Please check frontend also, some layout mess up if product has custom option.
> 
> 
> 2. No, this is Magento default database

**Comment by DAXIAPI** [comment]
we can use the dropdown,customer can check the product whether fit.This will realizel your requirements.
![qq 20170406101546](https://cloud.githubusercontent.com/assets/20631720/24734849/450e8b0c-1ab2-11e7-923a-15bf065f4ff1.png)
2.I still don't understand this function and where to show in Desktop.look a little confused.
![qq 20170406101753](https://cloud.githubusercontent.com/assets/20631720/24735037/6bb93d8c-1ab3-11e7-9af9-8ff2ff75cd5b.png)

**Comment by kevin-doselection** [comment]
1. Yes the function that can check the vehicle fitment can help user to find out their car 
If you have time, do this task first.

2. Don't worry. Put this out, The 1. function will do the same thing, then we will not need to make the 2. functional.

**Comment by kevin-doselection** [comment]
About 1. , desktop version can place at the same location as your image.
mobile version can you put it after SKU and center it?

**Comment by DAXIAPI** [comment]
ok,I will follow up.

**Comment by DAXIAPI** [comment]
I make like this.
![qq 20170411165859](https://cloud.githubusercontent.com/assets/20631720/24901127/a2c185d6-1ed8-11e7-882b-b758fabaa0e8.png)
![qq 20170411165947](https://cloud.githubusercontent.com/assets/20631720/24901128/a2d8d402-1ed8-11e7-80d9-bb06a450e705.png)
![qq 20170411170016](https://cloud.githubusercontent.com/assets/20631720/24901129/a2d96610-1ed8-11e7-9192-ab87971745d8.png)

**Comment by DAXIAPI** [comment]
Plese check it,thk.

**Comment by kevin-doselection** [comment]
Good.
Add on mobile version also
![image](https://cloud.githubusercontent.com/assets/17145866/24918506/84ebaafc-1e95-11e7-9af8-00b19f435162.png)

**Comment by DAXIAPI** [comment]
mobile version
![qq 20170412111605](https://cloud.githubusercontent.com/assets/20631720/24943789/c97e82d4-1f8a-11e7-8ce8-9ec2fc529ae0.png)
![qq 20170412111619](https://cloud.githubusercontent.com/assets/20631720/24943790/c97eca46-1f8a-11e7-9c54-6aa0c6e39bb2.png)

**Comment by kevin-doselection** [comment]
1. mobile version
Center it.
And can it shows without click?
2. desktop version
Show it after sku, before description
And can it shows without click also?
![image](https://cloud.githubusercontent.com/assets/17145866/24967140/fb7bb400-1f5d-11e7-9259-765fc76764cb.png)

**Comment by DAXIAPI** [comment]
1.I will do soon.
2.no,put in it will not work

**Comment by kevin-doselection** [comment]
Okay, but make your changes based on the latest version of ltsport.com
I saw some function was missing yesterday

**Comment by kevin-doselection** [comment]
1. Change "Fitment Check" result from text to image
`echo "It fits your car!";` Change to show image `https://www.ltsport.com/guide/confirmed_mobile.jpg`
`echo "It doesn't fit your car! `Change to show image  `https://www.ltsport.com/guide/anotherone_mobile.jpg`
Center these image and Check Fitment. Total 3 images need to adjust.
```
public function checkproAction(){
       $year = $_GET['year'];
       $make = $_GET['make'];
       $model = $_GET['model'];
       $sku = $_GET['sku'];     //"VSWV-ARSX0206-2D-201-WS";

       $product = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku);
       //$name = $product->getName();
       $yearString=$product->getData('year');
       $Year = explode(';', $yearString);
       $makeString=$product->getData('make');
       $Make = explode(';', $makeString);
       $modelString=$product->getData('v_model');
       $Model = explode(';', $modelString);
       for($index=0;$index<count($Year);$index++){
            if($Year[$index] == $year){
                for($index1=0;$index1<count($Make);$index1++){
                    if($Make[$index1] == $make){
                        for($index2=0;$index2<count($Model);$index2++)
                        {
                            if($Model[$index2] == $model){
                                echo "It fits your car!";
                                return;
                            }
                        }  
                    }
                    
                }  
            }          
        }  
        echo "It doesn't fit your car!";
    }
```

2. 
1) Center the dropdown list
2) directly show result when user already select year make model

![image](https://cloud.githubusercontent.com/assets/17145866/25048714/a78e4e84-20f2-11e7-9e2f-9f22b3426a4e.png)

3.mobile version homepage's dropdown search
if only https can work, please set only https will show
This one has year make model
and will direct forward user to result page, when year make model are all filled

**Comment by DAXIAPI** [comment]
1 and 2.ok
![qq 20170416110638](https://cloud.githubusercontent.com/assets/20631720/25069459/bedd5914-22b3-11e7-8d5a-380dd9ea0e37.png)
![qq 20170416110646](https://cloud.githubusercontent.com/assets/20631720/25069458/beda97a6-22b3-11e7-89a0-db05747b5f95.png)

**Comment by kevin-doselection** [comment]
3. you can suspend it now

additional task 1:
According to research, these 4 button are rarely been touch.
URL: https://www.ltsport.com/mobile_home
![image](https://cloud.githubusercontent.com/assets/17145866/25198408/465fdb38-24fc-11e7-97e7-73c049af85da.png)
Please create a slideshow (once at a time) by using these 6 imgs, and replace current 4 button.
Path: https://www.ltsport.com/mobile_shopbyproduct
![image](https://cloud.githubusercontent.com/assets/17145866/25198394/364a7c6c-24fc-11e7-9b0a-b9ac461db59e.png)

additional task 2: menu
1) contact info change link to https://www.ltsport.com/mobile_contact_us
2) add additional link called FAQ, and create a page for it. I will put content later, mostly question and answer format. 
3) move terms to footer, after installation guide. And remove customer login in the footer
4) footer, change name ourdoor carrier to bike rack, rooftop cargo to cargo basket, exterior guard to car cover
![image](https://cloud.githubusercontent.com/assets/17145866/25198492/95526b66-24fc-11e7-85fb-6a42b9fb1891.png)

additional task 3: search result
1) Text only shows after LT Sport (search results for honda civic 2015)
2) And show how many result was found.
URL: https://www.ltsport.com/catalogsearch/result/?q=honda+civic+2015
![image](https://cloud.githubusercontent.com/assets/17145866/25198928/db89a080-24fd-11e7-90c6-0ba9f7c1a4f3.png)

**Comment by DAXIAPI** [comment]
all have done
![qq 20170420162609](https://cloud.githubusercontent.com/assets/20631720/25221266/16101dc6-25e7-11e7-94aa-fd86eceb1c41.png)
![qq 20170420150219](https://cloud.githubusercontent.com/assets/20631720/25221276/202510aa-25e7-11e7-94fd-cb62561bee6a.png)
![qq 20170420162557](https://cloud.githubusercontent.com/assets/20631720/25221286/2e0b81ae-25e7-11e7-8884-d49ec6180e76.png)
![qq 20170420162543](https://cloud.githubusercontent.com/assets/20631720/25221297/358a7002-25e7-11e7-868e-fc202dac7c7a.png)

**Comment by kevin-doselection** [comment]
slideshow my mistake
I was saying place the slideshow to URL https://www.ltsport.com/mobile_home

![image](https://cloud.githubusercontent.com/assets/17145866/25238146/7463bd60-25a1-11e7-9057-3964d64c3ef8.png)

And for URL https://www.ltsport.com/mobile_shopbyproduct, it should remains the same  as below
![image](https://cloud.githubusercontent.com/assets/17145866/25238112/59dc70f4-25a1-11e7-8fee-44ab10273140.png)

Possible for smooth animation?

**Comment by kevin-doselection** [comment]
add the same slideshow after youtube video
![image](https://cloud.githubusercontent.com/assets/17145866/25362408/91e15586-2908-11e7-9065-1dc38c374348.png)

![image](https://cloud.githubusercontent.com/assets/17145866/25362394/805e28a2-2908-11e7-9f08-d0aab032a4c9.png)

**Comment by DAXIAPI** [comment]
It is difficult to log in to the server in China,so pls add the code as below.
path:"\ltsport.com\html\app\design\frontend\default\do2\template\catalog\product\list.phtml"
`<div class="cateContainer"><a id="abj" href="http://www.ltsport.com/findmyvehicle.html"><img id="obj" alt="" src="https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2visor.jpg" height="100%" width="100%" /></a></div>
<style></style>
<script type="text/javascript">// <![CDATA[
var curIndex = 0;
  var timeInterval = 3000;
  var arr = new Array();
  arr[0] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2visor.jpg";
  arr[1] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2rack.jpg";
  arr[2] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2mat.jpg";
  arr[3] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2cargo.jpg";
  arr[4] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2carrier.jpg";
  arr[5] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2guard.jpg";

var brr = new Array();
  brr[0] = "http://www.ltsport.com/products/visor.html";
  brr[1] = "http://www.ltsport.com/products/rack.html";
  brr[2] = "http://www.ltsport.com/products/mat.html";
  brr[3] = "http://www.ltsport.com/products/cargo.html";
  brr[4] = "http://www.ltsport.com/products/carrier.html";
  brr[5] = "http://www.ltsport.com/products/guard.html";

  setInterval(changeImg,timeInterval);
  function changeImg() {
   var obj = document.getElementById("obj");
   var abj = document.getElementById("abj");
   if (curIndex == arr.length-1) {
    curIndex = 0;
   } else {
    curIndex += 1;
     } 
	   obj.src = arr[curIndex];
  }
// ]]></script>
    height:100%;
    margin: 0 0 0 0;
    padding: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    zoom: 1;
}
--></style>
<script type="text/javascript">// <![CDATA[
var curIndex = 0;
  var timeInterval = 3000;
  var arr = new Array();
  arr[0] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2visor.jpg";
  arr[1] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2rack.jpg";
  arr[2] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2mat.jpg";
  arr[3] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2cargo.jpg";
  arr[4] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2carrier.jpg";
  arr[5] = "https://www.ltsport.com/skin/frontend/default/MAG050058/images/headerCategory/do2guard.jpg";

var brr = new Array();
  brr[0] = "http://www.ltsport.com/products/visor.html";
  brr[1] = "http://www.ltsport.com/products/rack.html";
  brr[2] = "http://www.ltsport.com/products/mat.html";
  brr[3] = "http://www.ltsport.com/products/cargo.html";
  brr[4] = "http://www.ltsport.com/products/carrier.html";
  brr[5] = "http://www.ltsport.com/products/guard.html";

  setInterval(changeImg,timeInterval);
  function changeImg() {
   var obj = document.getElementById("obj");
   var abj = document.getElementById("abj");
   if (curIndex == arr.length-1) {
    curIndex = 0;
   } else {
    curIndex += 1;
     } 
	   obj.src = arr[curIndex];
  }
// ]]></script>`
