### ISSUE TITLE
[ltsport.com] payment failed leads to order canceled

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#89]
If user's payment been declined, I want the website show popup message as below.

> Sorry, our system already canceled this order, since the payment was been declined by your card issuer.  Don't worry, we haven't charge any payment for this order. Please try another payment method and place another order. Thank you!

Order# 8547 & 8546& 8545
Current popup message when user's got declined. User will remains on the same checkout page.
`msg={"transaction_error":0,"transaction_approved":0,"exact_resp_code":"00","exact_message":"Transaction%20Normal","bank_resp_code":"303","bank_message":"Processor%20Decline","sequence_no":"0877345","avs":"2","retrieval_ref_no":"170406","merchant_name":"LT%20SPORT","merchant_address":"17005%20EVERGREEN%20PLACE%20%20A","merchant_city":"CITY%20OF%20INDUSTRY","merchant_province":"California","merchant_country":"United%20States","merchant_postal":"91745","merchant_url":"WWW.LTSPORT.COM","ctr":"==========%20TRANSACTION%20RECORD%20==========\nLT%20SPORT\n17005%20EVERGREEN%20PLACE%20%20A\nCITY%20OF%20INDUSTRY,%20CA%2091745\nUnited%20States\nWWW.LTSPORT.COM\n\nTYPE:%20Purchase\n\nACCT:%20American%20Express%20%20%20%20%20%20$%20130.68%20USD\n\nCARDHOLDER%20NAME%20:%20kevin%20yang\nCARD%20NUMBER%20%20%20%20%20:%20###########2508\nDATE/`

**Comment by DAXIAPI** [comment]
I don't understand website can decline to customer payment,pls tell me that next step I can solve the problem,thx.

**Comment by kevin-doselection** [comment]
This issue is because customer payment was been declined from their own card issuer. So we cannot accept that payment, and Magento will received declined message and changes the order status to Cancel. But user will not see any message about it.

**Comment by DAXIAPI** [comment]
Hi,Kevin,can you help me to create a new page?I tried but alway failed,so you can see if you can do it.This page will show when user's payment been declined.Thx!
name:payerror.phtml
path:/ltsport.com/html/app/design/frontend/default/MAG050058/template/checkout/payerror.html
content:`<div class="alpha60">
<p>Sorry, our system already canceled this order, since the payment was been declined by your card issuer. Don't worry, we haven't charge any payment for this order. Please try another payment method and place another order. Thank you!</p>
</div>`

**Comment by DAXIAPI** [comment]
pls hidden line 205 and show line 206 in path "/ltsport.com/html/app/code/local/Egs/Firstdata/controllers/IndexController.php",check it's working right.
![qq 20170419170618](https://cloud.githubusercontent.com/assets/20631720/25172280/0e84aca8-2523-11e7-8db5-58605641618b.png)

**Comment by kevin-doselection** [comment]
how is the result?

**Comment by DAXIAPI** [comment]
Yes,I have done but I'm not show it.Now you just hidden line 205 and show line 206 in path "/ltsport.com/html/app/code/local/Egs/Firstdata/controllers/IndexController.php",it can working.
result:when user's payment been declined,website will show popup message page.
I want you check this function does not affect other.Thx.

**Comment by kevin-doselection** [comment]
Change text content to below

> Sorry, your payment was declined by your card issuer. (Format H2)
> 
> For now our system already canceled this order, since the payment was been declined by your card issuer. 
>
> Don't worry, we haven't charge any payment for this order. 
> Please try another payment method and place another order. 
> 
> Thank you!



Before:
> Payerror
> Please complete this form, your question and request would be received by our customer service team, the representative would respond you in a short time.
> 
> cilck me to checkout

**Comment by DAXIAPI** [comment]
Is it ok?
![qq 20170421095138](https://cloud.githubusercontent.com/assets/20631720/25259445/af1050fe-2678-11e7-9a1a-9130d363834b.png)
![qq 20170421095123](https://cloud.githubusercontent.com/assets/20631720/25259468/d209d53a-2678-11e7-9876-860522368b50.png)

**Comment by kevin-doselection** [comment]
Yes
