### ISSUE TITLE
Walmart.com new items

### ISSUE THREAD

**Issue by kevin-doselection** [kevin-doselection/951753258#9]
沃尔玛新项目 pls send a task

**Comment by kevin-doselection** [comment]
http://seller.walmart.com
kyang12@go.pasadena.edu
qQ123456!

**Comment by DAXIAPI** [comment]
ok

**Comment by DAXIAPI** [comment]
@kevin-doselection Hi,kevin,I have downloaded Vehicle.xlsm and walmartfeed.csv,can you give me an example of a new items template?pls send it to me,thank you!
![qq 20160815114054](https://cloud.githubusercontent.com/assets/20631720/17655142/3061ee02-62dd-11e6-9700-9ada85374f56.jpg)

**Comment by kevin-doselection** [comment]
https://www.dropbox.com/sh/1c6z9vtlrzrkh6q/AABZu7L_kFtjS3KzhS6uORMMa?dl=0

**Comment by DAXIAPI** [comment]
ok
