### ISSUE TITLE
Company mailbox page go wrong in China

### ISSUE THREAD

**Issue by DAXIAPI** [kevin-doselection/951753258#90]
Hi,Kevin,ltsport.com mail looks bad in China,it 's hard to see it.I can't visit the code,so can you check it whether the CSS problem?
![qq 20170421160800](https://cloud.githubusercontent.com/assets/20631720/25268825/c8bbc98c-26ac-11e7-9427-40a9c5a25fe2.jpg)

**Comment by kevin-doselection** [comment]
Logout and login with dynamic mode
![image](https://cloud.githubusercontent.com/assets/17145866/25286466/b0e99486-2672-11e7-9298-36b151c2c92d.png)
